import { useEffect, useMemo, useRef, useState } from "react";
import { Camera, CheckCircle2, Clock3, LocateFixed, Pencil, RefreshCw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";

const base=String(import.meta.env.VITE_API_BASE||import.meta.env.BASE_URL||"").replace(/\/+$/,"").replace(/\/api$/,"");
const request=async(path:string,options?:RequestInit)=>{const response=await fetch(`${base}/api/crew/${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(options?.headers||{})},...options});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||`HTTP ${response.status}`)}return response.status===204?null:response.json()};
const isoToday=()=>new Date().toLocaleDateString("en-CA");
const statusCode:Record<string,string>={Present:"P",Late:"L",Absent:"A","Half Day":"HD","On Leave":"OL","Week Off":"WO",Holiday:"H",Remote:"R",WFH:"WFH"};
const statusTone:Record<string,string>={Present:"border-emerald-300 bg-emerald-50 text-emerald-700",Late:"border-amber-300 bg-amber-50 text-amber-700",Absent:"border-rose-300 bg-rose-50 text-rose-700","Half Day":"border-sky-300 bg-sky-50 text-sky-700","On Leave":"border-violet-300 bg-violet-50 text-violet-700","Week Off":"border-teal-300 bg-teal-50 text-teal-700",Holiday:"border-indigo-300 bg-indigo-50 text-indigo-700"};

export function AttendanceModule({employees,logs,user,can,refresh,edit}:{employees:any[];logs:any[];user:any;can:(permission:string)=>boolean;refresh:()=>Promise<void>;edit:(row:any)=>void}){
 const {toast}=useToast(),own=employees.find(employee=>Number(employee.id)===Number(user?.employeeId)),today=isoToday(),todayRecord=logs.find(log=>Number(log.employeeId)===Number(own?.id)&&log.attendanceDate===today);
 const mode=!todayRecord?.checkInTime?"punchIn":todayRecord?.checkOutTime?"completed":"punchOut";
 const [now,setNow]=useState(new Date()),[dialog,setDialog]=useState(false),[photo,setPhoto]=useState(""),[location,setLocation]=useState<any>(null),[locationError,setLocationError]=useState(""),[cameraError,setCameraError]=useState(""),[busy,setBusy]=useState(false),[from,setFrom]=useState(today),[to,setTo]=useState(today),[query,setQuery]=useState(""),[month,setMonth]=useState(today.slice(0,7)),[register,setRegister]=useState<any>(null),[registerLoading,setRegisterLoading]=useState(false);
 const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null);
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{setRegisterLoading(true);request(`attendance/register?month=${month}`).then(setRegister).catch((error)=>toast({title:"Unable to load attendance register",description:error.message,variant:"destructive"})).finally(()=>setRegisterLoading(false))},[month,logs.length]);
 const stopCamera=()=>{streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null};
 const acquireLocation=()=>{setLocation(null);setLocationError("");if(!navigator.geolocation){setLocationError("Location is not supported by this browser.");return}navigator.geolocation.getCurrentPosition(position=>setLocation({latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy,address:`${position.coords.latitude.toFixed(6)}, ${position.coords.longitude.toFixed(6)}`}),error=>setLocationError(error.message||"Unable to get location"),{enableHighAccuracy:true,timeout:10000,maximumAge:0})};
 const openPunch=async()=>{setPhoto("");setCameraError("");setDialog(true);acquireLocation();try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:480},height:{ideal:360}},audio:false});streamRef.current=stream;setTimeout(()=>{if(videoRef.current)videoRef.current.srcObject=stream},0)}catch(error:any){setCameraError(error.message||"Unable to open camera")}};
 const closePunch=()=>{stopCamera();setDialog(false)};
 const capture=async()=>{const video=videoRef.current;if(!video||!video.videoWidth)return;try{const Detector=(window as any).FaceDetector;if(Detector){const faces=await new Detector({fastMode:true,maxDetectedFaces:2}).detect(video);if(faces.length!==1){setCameraError(faces.length===0?"No face detected":"Only 1 person is allowed");return}}const canvas=document.createElement("canvas");canvas.width=480;canvas.height=360;canvas.getContext("2d")?.drawImage(video,0,0,480,360);setPhoto(canvas.toDataURL("image/jpeg",.85));setCameraError(Detector?"One face detected":"Photo captured. Face detector is unavailable on this device.")}catch(error:any){setCameraError(error.message||"Unable to capture photo")}};
 const confirm=async()=>{if(!own||!photo||!location)return;setBusy(true);try{if(mode==="punchOut")await request(`attendance/${todayRecord.id}`,{method:"PATCH",body:JSON.stringify({punchAction:"punchOut",photoDataUrl:photo,location,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});else await request("attendance",{method:"POST",body:JSON.stringify({employeeId:own.id,punchAction:"punchIn",photoDataUrl:photo,location,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});closePunch();await refresh();toast({title:mode==="punchOut"?"Punch out completed":"Punch in completed"})}catch(error:any){toast({title:"Punch failed",description:error.message,variant:"destructive"})}finally{setBusy(false)}};
 const filtered=useMemo(()=>logs.filter(log=>log.attendanceDate>=from&&log.attendanceDate<=to&&(!query||`${log.employeeName} ${log.status} ${log.notes||""}`.toLowerCase().includes(query.toLowerCase()))),[logs,from,to,query]);
 const days=register?Array.from({length:register.daysInMonth},(_,index)=>index+1):[];
 return <div className="space-y-6">
  <section className="rounded-xl border bg-card p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-semibold">Attendance</h2><p className="text-sm text-muted-foreground">Server time: {now.toLocaleTimeString("en-IN")}</p></div><span className="text-sm text-muted-foreground">{logs.length} records</span></div>
   <div className="rounded-lg border bg-muted/20 p-4"><p className="text-sm">Employee: <b>{own?`${own.name} (${own.employeeCode})`:"Linked employee not found"}</b></p><div className="mt-4 flex gap-2"><Button disabled={!own||mode==="completed"||!can("crew.attendance.create")} onClick={()=>void openPunch()}>{mode==="punchOut"?"Punch Out":mode==="completed"?"Attendance Completed":"Punch In"}</Button><Button variant="outline" onClick={()=>setNow(new Date())}><RefreshCw className="mr-2 h-4 w-4"/>Refresh Time</Button></div>{todayRecord&&<p className="mt-3 text-xs text-muted-foreground">Punch in: {todayRecord.checkInTime||"—"} · Punch out: {todayRecord.checkOutTime||"—"} · Status: {todayRecord.status}</p>}</div>
  </section>
  <section className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><h3 className="font-semibold">Latest attendance logs</h3><div className="flex flex-wrap items-center gap-2"><Input className="w-36" type="date" value={from} onChange={event=>setFrom(event.target.value)}/><span className="text-xs text-muted-foreground">to</span><Input className="w-36" type="date" value={to} onChange={event=>setTo(event.target.value)}/><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="w-56 pl-9" placeholder="Search attendance..." value={query} onChange={event=>setQuery(event.target.value)}/></div></div></div>
   <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr>{["Employee","Date","Status","Punch in","Punch out","Lock","Notes","Actions"].map(item=><th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{filtered.length?filtered.map(log=><tr key={log.id} className="border-t"><td className="px-4 py-3 font-medium">{log.employeeName}</td><td className="px-4 py-3">{log.attendanceDate}</td><td className="px-4 py-3">{log.status}</td><td className="px-4 py-3">{log.checkInTime||"—"}</td><td className="px-4 py-3">{log.checkOutTime||"—"}</td><td className="px-4 py-3">{log.locked?"Locked":"Open"}</td><td className="px-4 py-3 text-muted-foreground">{log.notes||"—"}</td><td className="px-4 py-3">{can("crew.attendance.update")&&<Button size="icon" variant="outline" className="h-8 w-8" aria-label="Edit attendance" onClick={()=>edit(log)}><Pencil className="h-4 w-4"/></Button>}</td></tr>):<tr><td colSpan={8} className="p-12 text-center text-muted-foreground">No attendance records found</td></tr>}</tbody></table></div><div className="border-t px-4 py-3 text-sm text-muted-foreground">Showing {filtered.length} records</div>
  </section>
  <section className="rounded-xl border bg-card p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-muted-foreground">Team matrix</p><h2 className="text-xl font-semibold">Monthly Attendance Register</h2></div><Input type="month" className="w-44" value={month} onChange={event=>setMonth(event.target.value)}/></div><div className="mb-4 flex flex-wrap gap-2">{Object.keys(statusCode).slice(0,7).map(status=><span key={status} className={`rounded-full border px-3 py-1 text-xs ${statusTone[status]||""}`}>{status}</span>)}</div>
   {registerLoading?<div className="p-12 text-center text-muted-foreground">Loading register...</div>:<div className="overflow-x-auto"><table className="min-w-max border-separate border-spacing-1 text-xs"><thead><tr><th className="sticky left-0 z-10 min-w-52 bg-card p-2 text-left">Employee</th>{days.map((day:any)=><th key={day} className="h-12 w-11 rounded-md border bg-muted/30 text-center"><b>{day}</b><small className="block text-muted-foreground">{new Date(`${month}-${String(day).padStart(2,"0")}T00:00:00`).toLocaleDateString("en",{weekday:"short"})}</small></th>)}</tr></thead><tbody>{(register?.rows||[]).map((row:any)=><tr key={row.employeeId}><td className="sticky left-0 z-10 rounded-md border bg-card p-3"><b>{row.employeeName}</b><small className="block text-muted-foreground">{row.employeeCode} · {row.department}</small></td>{row.days.map((cell:any)=><td key={cell.date} className="p-0.5"><span title={`${cell.date}: ${cell.status}`} className={`flex h-10 w-10 items-center justify-center rounded-md border font-semibold ${statusTone[cell.status]||"border-muted bg-muted/20"}`}>{statusCode[cell.status]||cell.status.slice(0,2)}</span></td>)}</tr>)}</tbody></table></div>}
  </section>
  <Dialog open={dialog} onOpenChange={open=>open?setDialog(true):closePunch()}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{mode==="punchOut"?"Punch Out":"Punch In"}</DialogTitle></DialogHeader><div className="space-y-4"><div className="overflow-hidden rounded-lg bg-black"><video ref={videoRef} autoPlay playsInline muted className="aspect-[4/3] w-full -scale-x-100 object-cover"/></div><div className="grid gap-3 sm:grid-cols-2"><div className={`rounded-md border p-3 text-sm ${photo?"border-emerald-300 bg-emerald-50":""}`}><Camera className="mb-1 h-4 w-4"/>{photo?"Photo captured":"Camera photo required"}</div><div className={`rounded-md border p-3 text-sm ${location?"border-emerald-300 bg-emerald-50":""}`}><LocateFixed className="mb-1 h-4 w-4"/>{location?location.address:locationError||"Getting current location..."}</div></div>{cameraError&&<p className="text-sm text-muted-foreground">{cameraError}</p>}<Button type="button" variant="outline" className="w-full" onClick={()=>void capture()}><Camera className="mr-2 h-4 w-4"/>Capture Photo</Button></div><DialogFooter><Button variant="outline" onClick={closePunch}>Cancel</Button><Button disabled={busy||!photo||!location} onClick={()=>void confirm()}>{busy?"Saving...":<><CheckCircle2 className="mr-2 h-4 w-4"/>Confirm {mode==="punchOut"?"Punch Out":"Punch In"}</>}</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}