import { useEffect, useMemo, useState } from "react";
import { Check, Eye, Pencil, Search, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

const root=String(import.meta.env.VITE_API_BASE||import.meta.env.BASE_URL||"").replace(/\/+$/,'').replace(/\/api$/,'');
const api=async(path:string,options?:RequestInit)=>{const response=await fetch(`${root}/api/crew/${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(options?.headers||{})},...options});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body};
const currency=(value:any)=>Number(value||0).toLocaleString("en-IN",{style:"currency",currency:"INR",minimumFractionDigits:2});
const tone:Record<string,string>={Calculated:"bg-sky-50 text-sky-700",Pending:"bg-amber-50 text-amber-700",Approved:"bg-emerald-50 text-emerald-700",Rejected:"bg-rose-50 text-rose-700",Cancelled:"bg-slate-100 text-slate-700"};

export function OvertimeModule({employees,user,can}:{employees:any[];user:any;can:(permission:string)=>boolean}){
 const {toast}=useToast(),own=employees.find(employee=>Number(employee.id)===Number(user?.employeeId)),canOthers=can("crew.overtime.forOthers"),defaultEmployee=String((canOthers?own||employees[0]:own)?.id||"");
 const [employeeId,setEmployeeId]=useState(defaultEmployee),[date,setDate]=useState(""),[title,setTitle]=useState(""),[notes,setNotes]=useState(""),[calculation,setCalculation]=useState<any>(null),[calculationError,setCalculationError]=useState(""),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[status,setStatus]=useState("All"),[crew,setCrew]=useState("All"),[selected,setSelected]=useState<any>(null);
 const load=async()=>{setLoading(true);try{setRows(await api("overtime"))}catch(error:any){toast({title:"Unable to load overtime",description:error.message,variant:"destructive"})}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 useEffect(()=>{setCalculation(null);setCalculationError("");if(!employeeId||!date)return;let active=true;api(`overtime/calculation?employeeId=${employeeId}&date=${date}`).then(value=>active&&setCalculation(value)).catch((error:any)=>active&&setCalculationError(error.message));return()=>{active=false}},[employeeId,date]);
 const submit=async()=>{if(!employeeId||!date||!title.trim()||!calculation){toast({title:"Select completed attendance with overtime and enter an OT title",variant:"destructive"});return}setBusy(true);try{await api("overtime",{method:"POST",body:JSON.stringify({employeeId:Number(employeeId),attendanceDate:date,title,notes})});toast({title:"Overtime submitted for approval"});setTitle("");setNotes("");setCalculation(null);setDate("");await load()}catch(error:any){toast({title:"Unable to submit overtime",description:error.message,variant:"destructive"})}finally{setBusy(false)}};
 const decide=async(row:any,next:"Approved"|"Rejected")=>{const remarks=next==="Rejected"?window.prompt("Enter rejection remarks (minimum 10 characters)")||"":"";if(next==="Rejected"&&remarks.trim().length<10){toast({title:"Rejection remarks must contain at least 10 characters",variant:"destructive"});return}try{await api(`overtime/${row.id}/status`,{method:"PATCH",body:JSON.stringify({status:next,rejectionRemarks:remarks})});toast({title:`Overtime ${next.toLowerCase()}`});setSelected(null);await load()}catch(error:any){toast({title:"Unable to update overtime",description:error.message,variant:"destructive"})}};
 const adjust=async(row:any)=>{const value=window.prompt("Enter adjusted overtime amount",String(row.amount));if(value===null)return;const amount=Number(value);if(!Number.isFinite(amount)||amount<0){toast({title:"Enter a valid non-negative amount",variant:"destructive"});return}try{const updated=await api(`overtime/${row.id}`,{method:"PATCH",body:JSON.stringify({amount})});toast({title:"Overtime amount adjusted"});setSelected(updated);await load()}catch(error:any){toast({title:"Unable to adjust amount",description:error.message,variant:"destructive"})}};
 const visible=useMemo(()=>rows.filter(row=>(!month||String(row.attendanceDate||row.createdAt).slice(0,7)===month)&&(status==="All"||row.status===status)&&(crew==="All"||String(row.employeeId)===crew)&&(!query||`${row.employeeName} ${row.title} ${row.notes||""} ${row.status} ${row.amount}`.toLowerCase().includes(query.toLowerCase()))),[rows,month,status,crew,query]);
 const pending=visible.filter(row=>row.status==="Pending").length,approved=visible.filter(row=>row.status==="Approved").reduce((sum,row)=>sum+Number(row.amount||0),0);
 return <div className="space-y-6">
  <div className="grid gap-4 md:grid-cols-3"><Metric label="Pending" value={pending}/><Metric label="Approved OT amount" value={currency(approved)} green/><Metric label="Scope" value={canOthers?"Team queue":"My requests"}/></div>
  <section className="rounded-xl border bg-card p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">OTS</p><h2 className="mb-5 text-xl font-bold">Overtime claims</h2><div className="grid gap-3 lg:grid-cols-5">
   <Field label="Select employee *"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={employeeId} disabled={!canOthers} onChange={event=>setEmployeeId(event.target.value)}><option value="">Select employee</option>{employees.filter(employee=>employee.status!=="Offboarded").map(employee=><option key={employee.id} value={employee.id}>{employee.name} ({employee.employeeCode})</option>)}</select></Field>
   <Field label="OT title *"><Input placeholder="OT title" maxLength={160} value={title} onChange={event=>setTitle(event.target.value)}/></Field><Field label="Amount"><Input readOnly value={calculation?.amount??0}/></Field><Field label="Attendance date *"><Input type="date" value={date} onChange={event=>setDate(event.target.value)}/></Field><div className="flex items-end"><Button className="w-full" disabled={busy||!calculation||!can("crew.overtime.create")} onClick={()=>void submit()}>{busy?"Submitting...":"Submit OT"}</Button></div>
  </div>{calculationError&&<p className="mt-3 rounded-md bg-rose-50 px-3 py-2 text-sm text-rose-700">{calculationError}</p>}{calculation&&<div className="mt-4 grid gap-3 rounded-lg border bg-muted/20 p-4 sm:grid-cols-3 lg:grid-cols-6"><Detail label="OT hours" value={`${calculation.overtimeHours} hrs`}/><Detail label="OT minutes" value={calculation.totalOvertimeMinutes}/><Detail label="Punch in" value={calculation.checkInTime}/><Detail label="Punch out" value={calculation.checkOutTime}/><Detail label="Shift" value={`${calculation.workStartTime}–${calculation.workEndTime}`}/><Detail label="Hourly rate" value={currency(calculation.hourlySalary)}/></div>}<div className="mt-4"><Label>Notes (optional)</Label><Textarea className="mt-1 min-h-20" placeholder="Add overtime details" value={notes} onChange={event=>setNotes(event.target.value)}/></div>
   <div className="mt-4 grid gap-3 md:grid-cols-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search overtime claims" value={query} onChange={event=>setQuery(event.target.value)}/></div><Input type="month" value={month} onChange={event=>setMonth(event.target.value)}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={status} onChange={event=>setStatus(event.target.value)}>{["All","Calculated","Pending","Approved","Rejected","Cancelled"].map(value=><option key={value} value={value}>{value==="All"?"All statuses":value}</option>)}</select><select className="h-10 rounded-md border bg-background px-3 text-sm" value={crew} onChange={event=>setCrew(event.target.value)}><option value="All">All crew</option>{employees.map(employee=><option key={employee.id} value={employee.id}>{employee.name}</option>)}</select></div>
  </section>
  <section className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr>{["Employee","Title","Hours","Amount","Date","Status","Actions"].map(value=><th key={value} className="px-4 py-3">{value}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-12 text-center text-muted-foreground">Loading overtime...</td></tr>:visible.length?visible.map(row=><tr key={row.id} className="border-t"><td className="px-4 py-3 font-medium">{row.employeeName}</td><td className="px-4 py-3">{row.title}</td><td className="px-4 py-3">{row.requestedHours||"—"}</td><td className="px-4 py-3 font-medium">{currency(row.amount)}</td><td className="px-4 py-3">{row.attendanceDate}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone[row.status]||""}`}>{row.status}</span></td><td className="px-4 py-3"><Button size="icon" variant="outline" className="h-8 w-8" onClick={()=>setSelected(row)}><Eye className="h-4 w-4"/></Button></td></tr>):<tr><td colSpan={7} className="p-12 text-center text-muted-foreground">No overtime claims found</td></tr>}</tbody></table></div><div className="border-t px-4 py-3 text-sm text-muted-foreground">Showing {visible.length} of {rows.length} records</div></section>
  <Dialog open={Boolean(selected)} onOpenChange={open=>!open&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>Overtime Details</DialogTitle></DialogHeader>{selected&&<div className="space-y-4"><div className="grid gap-3 text-sm sm:grid-cols-2"><Detail label="Employee" value={selected.employeeName}/><Detail label="Status" value={selected.status}/><Detail label="Attendance date" value={selected.attendanceDate}/><Detail label="Hours" value={`${selected.requestedHours} hrs`}/><Detail label="Amount" value={currency(selected.amount)}/><Detail label="Title" value={selected.title}/><div className="sm:col-span-2"><Detail label="Notes" value={selected.notes||"No notes"}/></div>{selected.rejectionRemarks&&<div className="sm:col-span-2 text-destructive"><Detail label="Rejection remarks" value={selected.rejectionRemarks}/></div>}</div>{selected.status==="Pending"&&<div className="flex flex-wrap justify-end gap-2">{can("crew.overtime.update")&&<Button variant="outline" onClick={()=>void adjust(selected)}><Pencil className="mr-2 h-4 w-4"/>Adjust amount</Button>}{can("crew.overtime.reject")&&<Button variant="outline" className="text-destructive" onClick={()=>void decide(selected,"Rejected")}><X className="mr-2 h-4 w-4"/>Reject</Button>}{can("crew.overtime.approve")&&<Button onClick={()=>void decide(selected,"Approved")}><Check className="mr-2 h-4 w-4"/>Approve</Button>}</div>}</div>}</DialogContent></Dialog>
 </div>
}
function Metric({label,value,green=false}:{label:string;value:any;green?:boolean}){return <div className="rounded-xl border bg-card p-4 shadow-sm"><p className="text-xs font-semibold uppercase text-muted-foreground">{label}</p><p className={`mt-1 text-2xl font-bold ${green?"text-emerald-600":""}`}>{value}</p></div>}
function Field({label,children}:{label:string;children:any}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Detail({label,value}:{label:string;value:any}){return <div><span className="text-xs text-muted-foreground">{label}</span><b className="block">{value??"—"}</b></div>}
