/** User-facing copy for the Flex module. */
export const FLEX_TEXT = {
  autoAssignedOnSave: "Auto-assigned on save",
  action: "ACTION",
  actions: "ACTIONS",
  activeVendors: "Active Vendors",
  addBlankRow: "+ Add blank row",
  addContact: "Add Contact",
  addInventory: "Add Inventory",
  addItem: "+ Add Item",
  additionalNotes: "Additional notes",
  addLine: "+ Add Line",
  addLineItemsManuallyOrMapPurchaseOrderSAboveToAutoFillVendorAndItems:
    "Add line items manually or map purchase order(s) above to\n                    auto-fill vendor and items.",
  address: "Address *",
  addToItemMaster: "+ Add to Item Master",
  addVendor: "+ Add Vendor",
  addWarehouse: "+ Add Warehouse",
  admin: "Admin",
  allVendors: "All vendors",
  amount: "AMOUNT",
  approvalWorkflowActions: "Approval & Workflow Actions",
  approvePo: "Approve PO",
  approveRequest: "Approve\n                          Request",
  atLeastOneLineItemIsRequired: "At least one line item is required.",
  attachGoodsDeliverySlipPhotoOptional:
    "Attach Goods Delivery Slip / Photo (optional)",
  attachment: "Attachment:",
  bags: "bags",
  bangalore4: "Bangalore (4)",
  bankAccount10201: "Bank Account (1020) (1)",
  bankCashAccount: "Bank / Cash account",
  bankTransfer: "Bank Transfer",
  bill: "BILL #",
  buyingPrice: "Buying Price (₹) *",
  cancel: "Cancel",
  cash: "Cash",
  category: "Category *",
  cclm112000: "CCLM-1 (₹ 12,000)",
  cgst: "CGST%",
  cgst2: "CGST",
  chennai2: "Chennai (2)",
  cheque: "Cheque",
  chooseFile: "Choose File",
  clickToAttachFile: "Click to attach file",
  close: "Close",
  coimbatore1: "Coimbatore (1)",
  consumable: "Consumable",
  contactId: "Contact ID",
  contactPerson: "Contact Person",
  contactPerson2: "Contact Person:",
  contactPersonName: "Contact person name",
  contactType: "Contact Type",
  couldnTLoadTheDashboardTryAgain: "Couldn't load the dashboard. Try again.",
  createPo: "Create PO",
  createPr: "Create PR",
  createPurchaseRequest: "Create Purchase Request",
  createsANewEntryInOrbitContactDirectory:
    "Creates a new entry in Orbit Contact Directory.",
  critical: "Critical",
  criticalLevel: "Critical Level",
  currentStatus: "Current Status:",
  customSpecification: "Custom specification",
  dashboard: "Dashboard",
  date: "DATE",
  delete: "Delete",
  deliveryDate: "DELIVERY DATE",
  deliveryDate2: "Delivery Date",
  department: "DEPARTMENT",
  department2: "Department:",
  department3: "Department",
  departmentTeam: "Department / Team",
  describeDefect: "Describe defect...",
  description: "DESCRIPTION",
  description2: "Description",
  destinationWarehouse: "Destination Warehouse",
  details: "Details",
  development: "Development",
  duplicatePo: "Duplicate PO",
  duplicatePr: "Duplicate PR",
  editPurchaseRequest: "Edit Purchase Request",
  eG1500: "e.g. 1500",
  email: "Email",
  email2: "EMAIL",
  emailAddress: "Email address",
  engineering: "Engineering",
  enterVendorName: "Enter vendor name",
  erpUpgrade: "ERP Upgrade",
  filterByVendor: "Filter by vendor",
  finishedGoods: "Finished Goods",
  fromDate: "From Date",
  generalProcurement: "General Procurement",
  generatedSku: "Generated SKU *",
  generatePurchaseOrder: "Generate\n                        Purchase Order",
  goodsReceiptLoggedSuccessfully: "Goods Receipt logged successfully",
  goodsReceiptLoggedSuccessfully2: "Goods Receipt logged successfully!",
  goodsReceipts: "Goods Receipts",
  goodsReceiptsGrn: "Goods Receipts (GRN)",
  grandTotal: "GRAND TOTAL",
  grandTotal2: "Grand Total",
  grandTotal3: "Grand Total:",
  grn: "GRN #",
  grnAmount: "GRN Amount",
  grnAmt: "GRN AMT",
  grnNumber: "GRN Number",
  grnRef: "GRN REF",
  gstin: "GSTIN",
  gstNumber: "GST number",
  gstNumber2: "GST Number",
  hardware: "Hardware",
  high: "High",
  hsn: "HSN",
  hsnSac: "HSN/SAC *",
  igst: "IGST%",
  initiatePurchaseReturn: "Initiate Purchase Return",
  initiateReturn: "Initiate Return",
  invoice: "INVOICE #",
  invoiceAmount: "Invoice Amount",
  invoiceAmt: "INVOICE AMT",
  invoiceAttachment: "Invoice Attachment",
  invoiceDate: "Invoice Date",
  invoiceNumber: "Invoice Number",
  invoiceTotalAmountRs: "Invoice Total Amount (Rs)",
  itemName: "Item Name *",
  itemName2: "Item Name:",
  itemProduct: "Item / Product",
  itemProductAsset: "ITEM / PRODUCT / ASSET",
  kg: "kg",
  lineItems: "Line Items",
  lineItems2: "LINE ITEMS",
  loading: "Loading…",
  logGoodsReceipt: "Log Goods Receipt",
  logInvoice: "Log Invoice",
  logistics: "Logistics",
  logPurchaseInvoice: "Log Purchase Invoice",
  logReceipt: "Log Receipt",
  low: "Low",
  maintenance: "Maintenance",
  mapEitherPurchaseOrderSOrGoodsReceiptSSelectOneSourceTypeOnlyMultiSelectIsAllowedWithinTheSameType:
    "Map either purchase order(s) or goods receipt(s). Select one\n                    source type only. Multi-select is allowed within the same\n                    type.",
  mapGoodsReceiptS: "Map Goods Receipt(s)",
  mapPurchaseOrderS: "Map Purchase Order(s)",
  markCompleted: "Mark Completed",
  markDispatched: "Mark Dispatched",
  match: "MATCH",
  matchPreview: "Match Preview",
  markMatched: "Mark Matched",
  invoiceMarkedAsMatched: "Invoice marked as Matched.",
  neftRtgs: "NEFT/RTGS",
  noAuditHistoryAvailable: "No audit history available.",
  noGoodsReceiptNotesFound: "No goods receipt notes found.",
  noLineItemsYetAddItemsManuallyOrMapPurchaseOrderS:
    "No line items yet. Add items manually or map purchase\n                      order(s).",
  noLineItemsYetMapPoGrOrAddItemsManually:
    "No line items yet. Map PO/GR or add items manually.",
  noOutstandingBillsFound: "No outstanding bills found.",
  noVendorsFound: "No vendors found.",
  notAvailable: "�",
  removeVendorFromRequest: "Remove vendor from this purchase request",
  noPoLinked: "No PO Linked",
  noPurchaseInvoicesFound: "No purchase invoices found.",
  noPurchaseOrdersFound: "No purchase orders found.",
  noPurchaseRequestsFound: "No purchase requests found.",
  noPurchaseReturnsRecordedYet: "No purchase returns recorded yet.",
  noRecentActivity: "No recent activity.",
  normal: "Normal",
  nos: "Nos",
  notes: "Notes",
  noVendorActivityYet: "No vendor activity yet.",
  of: "of",
  onTime: "On-time",
  ootySolarPanelInstallation: "Ooty Solar Panel Installation",
  optional: "Optional...",
  optionalPaymentNotes: "Optional payment notes",
  outstanding: "OUTSTANDING",
  outstandingBill: "Outstanding bill",
  outstandingBills: "Outstanding Bills",
  packaging: "Packaging",
  paid: "PAID",
  payment: "PAYMENT",
  paymentAmount: "Payment amount",
  paymentDate: "Payment date",
  paymentMode: "Payment mode",
  paymentRecordedAgainstBill: "Payment recorded against bill",
  paymentTermsDeliveryConditions: "Payment terms, delivery conditions...",
  pcs: "pcs",
  pdfJpgPngWebpMax250Kb: "PDF, JPG, PNG, WebP - Max 250 KB",
  pending: "PENDING",
  pettyCash1010: "Petty Cash (1010)",
  phone: "Phone *",
  phone2: "PHONE",
  phoneNumber: "Phone number",
  placeOfSupplyStateCode: "Place of Supply (State Code)",
  pleaseEnterItemName: "Please enter item name",
  pleaseEnterVendorName: "Please enter vendor name",
  pleaseEnterVendorNameAndReason: "Please enter vendor name and reason",
  po: "PO #",
  poAmt: "PO AMT",
  poApprovalWorkflowActions:
    "PO\n                    Approval & Workflow Actions",
  poDate: "PO DATE",
  poDate2: "PO Date",
  poNumber: "PO Number",
  price: "PRICE",
  print: "Print",
  printGrn: "Print GRN",
  printInvoice: "Print Invoice",
  printPo: "Print PO",
  printPr: "Print PR",
  priority: "PRIORITY",
  priority2: "Priority",
  prNumber: "PR NUMBER",
  procurementControlTower: "Procurement Control Tower",
  productImage: "Product Image",
  production: "Production",
  productQrCodeCompleteCategorySelectionsToGenerateTheQrCode:
    "Product QR Code: Complete category selections to generate the\n                  QR code.",
  project: "Project",
  project2: "Project:",
  purchaseInvoiceLoggedSuccessfully: "Purchase invoice logged successfully",
  purchaseInvoiceLoggedSuccessfully2: "Purchase Invoice logged successfully!",
  purchaseInvoices: "Purchase Invoices",
  purchaseOrderBuilder: "Purchase Order Builder",
  purchaseOrderDeleted: "Purchase Order deleted",
  purchaseOrderGeneratedFromApprovedPr:
    "Purchase Order generated from approved PR!",
  purchaseOrders: "Purchase Orders",
  purchaseOrderUpdatedSuccessfully: "Purchase Order updated successfully",
  purchaseRequestDeleted: "Purchase Request deleted",
  purchaseRequestNumber: "PURCHASE REQUEST NUMBER",
  purchaseRequests: "Purchase Requests",
  purchaseRequestUpdatedSuccessfully: "Purchase Request updated successfully",
  purchaseRequestUpdatedSuccessfully2: "Purchase Request updated successfully!",
  purchaseReturnInitiatedSuccessfully: "Purchase Return initiated successfully",
  purchaseReturns: "Purchase Returns",
  qty: "QTY",
  qty2: "Qty",
  quantity: "Quantity:",
  quote: "Quote:",
  rate: "RATE",
  rawMaterial: "Raw Material",
  reason: "REASON",
  reasonForReturn: "Reason for Return *",
  receivedBy: "RECEIVED BY",
  receivedBy2: "Received By",
  receivedDate: "RECEIVED DATE",
  receivedDate2: "Received Date",
  receivedOrdered: "RECEIVED / ORDERED",
  recentActivities: "Recent Activities",
  recordPayment: "Record Payment",
  recordPaymentsAgainstVendorBillsAndUpdateAccountsPayable:
    "Record payments against vendor bills and update accounts payable.",
  records: "records",
  recordVendorPayment: "Record Vendor Payment",
  recvQty: "RECV QTY",
  refreshedGoodsReceipts: "Refreshed Goods Receipts",
  refreshedPurchaseInvoices: "Refreshed Purchase Invoices",
  refreshedPurchaseOrders: "Refreshed Purchase Orders",
  refreshedPurchaseRequests: "Refreshed Purchase Requests",
  refreshRecords: "Refresh Records",
  refundAmount: "Refund Amount (₹)",
  refundAmt: "REFUND AMT",
  rejectPo: "Reject PO",
  rejectRequest: "Reject Request",
  reqDate: "REQ DATE",
  requestDate: "Request Date",
  requestedBy: "REQUESTED BY",
  requestedBy2: "Requested By",
  requestedBy3: "Requested By:",
  requestNumber: "REQUEST NUMBER",
  requiredDate: "REQUIRED DATE",
  requiredDate2: "Required Date",
  reSubmitRequest: "Re-submit Request",
  return: "RETURN #",
  returns: "Returns",
  rowsPerPage: "Rows per page:",
  sales: "Sales",
  sameVendorOnlyGrnAmountsAreSummedForMatching:
    "Same vendor only. GRN amounts are summed for matching.",
  sameVendorOnlyPoAmountsAreSummedForMatching:
    "Same vendor only. PO amounts are summed for matching.",
  save: "Save",
  saveDraft: "Save Draft",
  saveSend: "Save & Send",
  savingWillCreateANewSubmittedVersionFromThisLockedRequest:
    "Saving will create a new submitted version from this locked\n                  request.",
  searchByItemSkuRequesterOrVendorIdCon:
    "Search by Item, SKU, requester or Vendor ID (CON...)...",
  searchGoodsReceiptsOrVendorIdCon:
    "Search goods receipts or Vendor ID (CON...)...",
  searchOrSelectCategory: "Search or select category",
  searchOrSelectItem: "Search or select item",
  searchPosOrVendorIdCon: "Search POs or Vendor ID (CON...)...",
  searchPurchaseInvoicesOrVendorIdCon:
    "Search purchase invoices or Vendor ID (CON...)...",
  searchPurchaseReturnsOrVendorIdCon:
    "Search purchase returns or Vendor ID (CON...)...",
  searchVendors: "Search vendors...",
  selectBill: "Select bill",
  selectDepartment: "Select department...",
  selectEmployee: "Select employee...",
  selectMasterItem: "Select master item...",
  selectOrTypeItemService: "Select or type item/service",
  selectOrTypeProductService: "Select or type product/service",
  selectOrTypeVendor: "Select or type vendor",
  selectPaymentMode: "Select payment mode",
  selectVendor: "Select Vendor",
  selectVendor2: "Select vendor",
  selectWarehouseForStock: "Select warehouse for stock...",
  sellingPrice: "Selling Price (₹) *",
  sgst: "SGST%",
  sgst2: "SGST",
  sheets: "sheets",
  showing: "Showing",
  spend: "Spend",
  standardSheet: "Standard Sheet",
  status: "STATUS",
  stockByWarehouse: "Stock by Warehouse",
  submitRequest: "Submit Request",
  submitReturn: "Submit Return",
  subtotal: "SUBTOTAL",
  subtotal2: "Subtotal",
  subtotal3: "Subtotal:",
  supportingAttachments: "Supporting Attachments",
  supportingDocumentOptional: "Supporting Document (optional)",
  tax: "TAX (%)",
  termsConditions: "Terms & Conditions",
  text2WayMatchPreview: "2-WAY MATCH PREVIEW",
  to: "to",
  toDate: "To Date",
  topVendors: "Top Vendors",
  total: "TOTAL",
  totalAmount: "Total Amount: ₹",
  totalSpend: "Total Spend",
  trackedInAnalytics: "tracked in analytics",
  transactionReference: "Transaction reference",
  type: "Type",
  typeToFilter: "Type to filter...",
  typeToFilterAndSelectGoodsReceiptS:
    "Type to filter and select goods receipt(s)...",
  typeToFilterAndSelectPurchaseOrderS:
    "Type to filter and select purchase order(s)...",
  unit: "Unit",
  units: "units",
  uom: "UOM *",
  upi: "UPI",
  upiChequeNeftReference: "UPI / cheque / NEFT reference",
  uploadImage: "Upload image",
  urgent: "Urgent",
  vendor: "Vendor",
  vendor2: "VENDOR",
  vendor3: "Vendor:",
  vendorAddress: "Vendor Address",
  vendorAddress2: "Vendor address",
  vendorAvailability: "Vendor Availability",
  vendorContactPerson: "Vendor contact person",
  vendorGst: "Vendor GST",
  vendorGst2: "Vendor GST:",
  vendorId: "VENDOR ID",
  vendorName: "Vendor Name",
  vendorName2: "Vendor Name *",
  vendorName3: "VENDOR NAME",
  vendorPaymentRecordedSuccessfully: "Vendor payment recorded successfully!",
  vendorPayments: "Vendor Payments",
  vendorPhone: "Vendor Phone",
  vendorPhone2: "Vendor phone",
  vendorPhone3: "Vendor Phone:",
  vendorQuotesFor: "Vendor Quotes for",
  vendors: "Vendors (",
  vendorSelection: "Vendor Selection",
  version: "VERSION",
  versionAuditHistory: "Version\n                    Audit History",
  viewEditPo: "View / Edit PO",
  vsLastMonth: "% vs last month",
  warehouse: "WAREHOUSE",
  warehouse2: "Warehouse:",
  whatsapp: "WhatsApp",
  whatsapp2: "WHATSAPP",
  whatsappNumber: "WhatsApp number",
  x: "x ₹",
  printDate: "Date:",
  printDepartment: "Department:",
  printDescription: "Description",
  printGoodsDeliveryBilling: "Goods Delivery Billing",
  printGrandTotal: "Grand Total",
  printGrnAmount: "GRN Amount",
  printItemName: "Item Name",
  printItemsDescription: "Items Description",
  printMatch: "Match",
  printPlaceOfSupply: "Place of Supply:",
  printPoAmount: "PO Amount",
  printPoRef: "PO Ref:",
  printPoReference: "PO Reference:",
  printPriority: "Priority:",
  printQty: "Qty",
  printReceivedBy: "Received By:",
  printReceivedDate: "Received Date:",
  printRequestedBy: "Requested By:",
  printRequiredDate: "Required Date:",
  printStatus: "Status:",
  printSubtotal: "Subtotal",
  printUnit: "Unit",
  printVendor: "Vendor:",
  printWarehouse: "Warehouse:",
  noReturnsRecorded: "No returns recorded",
  openVendorResponses: "Open Vendor Responses",
  pendingGrns: "Pending GRNs",
  pendingPos: "Pending POs",
  pendingPurchaseRequests: "Pending Purchase Requests",
  recorded: "recorded",
  savedVendorToVendorDirectory: "Saved vendor to Vendor Directory: ",
  unpaidInvoices: "Unpaid Invoices",
  attached: "Attached ",
  duplicatingDetailsFrom: "Duplicating details from ",
  failedToConvertPrToPurchaseOrder: "Failed to convert PR to Purchase Order",
  failedToCreateGrn: "Failed to create GRN",
  failedToCreatePo: "Failed to create PO",
  failedToCreatePr: "Failed to create PR",
  failedToDeletePo: "Failed to delete PO",
  failedToDeletePr: "Failed to delete PR",
  failedToGeneratePo: "Failed to generate PO",
  failedToInitiateReturn: "Failed to initiate return",
  failedToLoadFlexDashboard: "Failed to load Flex dashboard",
  failedToLoadVendorAndItemMasterData: "Failed to load vendors and items.",
  loadingItems: "Loading items...",
  loadingDepartments: "Loading departments...",
  noDepartmentsAvailable: "No departments available",
  failedToLoadDepartments: "Failed to load departments",
  loadingVendors: "Loading vendors...",
  failedToLogGrn: "Failed to log GRN",
  failedToLogInvoice: "Failed to log invoice",
  failedToRecordPayment: "Failed to record payment",
  failedToSaveVendorContact: "Failed to save vendor contact",
  failedToUpdatePo: "Failed to update PO",
  failedToUpdatePr: "Failed to update PR",
  inventoryItemAdded: "Inventory Item added: ",
  purchaseOrderCreatedSuccessfully: "Purchase Order created successfully",
  purchaseOrderSavedAsDraft: "Purchase Order saved as Draft",
  purchaseRequestCreatedSuccessfully: "Purchase Request created successfully",
  purchaseRequestSavedAsDraft: "Purchase Request saved as Draft",
} as const;
