import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import locationsRouter from "./locations";
import alertColorsRouter from "./alertColors";
import materialsRouter from "./materials";
import inventoryRouter from "./inventory";
import spawnRouter from "./spawn";
import batchesRouter from "./batches";
import chambersRouter from "./chambers";
import dashboardRouter from "./dashboard";
import coimbatoreRouter from "./coimbatore";
import labRouter from "./lab";
import ootyRouter from "./ooty";
import traceabilityRouter from "./traceability";
import schedulingRouter from "./scheduling";
import salesRouter from "./sales";
import fleetRouter from "./fleet";
import reportsRouter from "./reports";
import rolesRouter from "./roles";
import tasksRouter from "./tasks";
import contactsRouter from "./contacts";
import templatesRouter from "./templates";
import permissionsRouter from "./permissions";
import flexRouter from "./flex";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/settings/users", usersRouter);
router.use("/locations", locationsRouter);
router.use("/alert-colors", alertColorsRouter);
router.use("/materials", materialsRouter);
router.use("/inventory", inventoryRouter);
router.use("/spawn", spawnRouter);
router.use("/batches", batchesRouter);
router.use("/chambers", chambersRouter);
router.use("/dashboard", dashboardRouter);
router.use("/coimbatore", coimbatoreRouter);
router.use("/lab", labRouter);
router.use("/ooty", ootyRouter);
router.use("/traceability", traceabilityRouter);
router.use("/scheduling", schedulingRouter);
router.use("/sales", salesRouter);
router.use("/fleet", fleetRouter);
router.use("/reports", reportsRouter);
router.use("/roles", rolesRouter);
router.use("/settings/roles", rolesRouter);
router.use("/tasks", tasksRouter);
router.use("/contacts", contactsRouter);
router.use(templatesRouter);
router.use("/settings", templatesRouter);
router.use(permissionsRouter);
router.use("/flex", flexRouter);

export default router;
