import { Router } from "express";
import { z } from "zod/v4";
import { and, asc, db, eq, attendanceTemplatesTable, workPatternTemplatesTable, salaryTemplatesTable, holidayTemplatesTable, leaveTemplatesTable } from "@workspace/db";
import { organizationId, requirePermission } from "../lib/access";

const router = Router();
const name = z.string().trim().min(1).max(120);
const time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const nonnegative = z.coerce.number().min(0);
const weekdayList = z.array(z.coerce.number().int().min(0).max(6)).transform(v => [...new Set(v)].sort());
const common = { templateName: name, isDefault: z.boolean().default(false) };

const attendance = z.object({ ...common, flexibleHours: z.boolean().default(false), lateThresholdMinutes: nonnegative.int(), workStartTime: time, workEndTime: time, fineType: z.enum(["fixed_per_hour", "percent_hourly_basis"]), finePerHour: nonnegative });
const workPattern = z.object({ ...common, week1OffDays: weekdayList, week2OffDays: weekdayList, week3OffDays: weekdayList, week4OffDays: weekdayList, week5OffDays: weekdayList });
const component = z.object({ id: z.string().min(1), name: z.string().min(1), calculationType: z.enum(["fixed", "percentage_of_ctc", "percentage_of_component", "residual"]), value: z.string().nullable().optional(), referenceComponentId: z.string().nullable().optional(), order: z.number().int().positive() }).superRefine((v, ctx) => { const n=Number(v.value); if (v.calculationType !== "residual" && (!Number.isFinite(n) || n < 0)) ctx.addIssue({ code:"custom", message:"A non-negative value is required" }); if (v.calculationType.startsWith("percentage") && n > 100) ctx.addIssue({ code:"custom", message:"Percentage cannot exceed 100" }); if (v.calculationType === "percentage_of_component" && !v.referenceComponentId) ctx.addIssue({ code:"custom", message:"Reference component is required" }); });
const salary = z.object({ ...common, description: z.string().max(500).nullable().optional(), components: z.array(component).min(1) }).superRefine((v,ctx)=>{if(new Set(v.components.map(c=>c.id)).size!==v.components.length)ctx.addIssue({code:"custom",message:"Salary components must be unique"});});
const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const holiday = z.object({ ...common, effectiveYear: z.number().int().min(1970).max(3000), effectiveFrom: isoDate, holidays: z.array(z.object({ name: z.string().trim().min(1).max(120), date: isoDate })) }).superRefine((v,ctx)=>{if(Number(v.effectiveFrom.slice(0,4))!==v.effectiveYear)ctx.addIssue({code:"custom",message:"Effective date must be within the selected year"});});
const leave = z.object({ ...common, totalSickLeaves: nonnegative, totalCasualLeaves: nonnegative, earnedLeave: nonnegative, maxSickLeavesPerMonth: nonnegative, maxCasualLeavesPerMonth: nonnegative, maxEarnedLeavesPerMonth: nonnegative, carryForwardEnabled: z.boolean().default(true) });

const configs: Record<string, { table:any; schema:z.ZodTypeAny; json:string[]; ensureDefault?:boolean }> = {
  "attendance-templates": { table: attendanceTemplatesTable, schema: attendance, json: [] },
  "work-pattern-templates": { table: workPatternTemplatesTable, schema: workPattern, json: ["week1OffDays","week2OffDays","week3OffDays","week4OffDays","week5OffDays"], ensureDefault: true },
  "salary-templates": { table: salaryTemplatesTable, schema: salary, json: ["components"] },
  "holiday-templates": { table: holidayTemplatesTable, schema: holiday, json: ["holidays"], ensureDefault: true },
  "leave-templates": { table: leaveTemplatesTable, schema: leave, json: [], ensureDefault: true },
};

const decode = (row:any, fields:string[]) => ({ ...row, ...Object.fromEntries(fields.map(k=>[k, (()=>{try{return JSON.parse(row[k]??"[]")}catch{return []}})()])), ...(row.effectiveYear ? holidayMeta(row) : {}) });
const holidayMeta = (row:any) => { const today=new Date().toISOString().slice(0,10), end=`${row.effectiveYear}-12-31`; const lifecycleStatus=end<today?"expired":row.effectiveFrom<=today?"active":"expiring-soon"; return { templateRef:String(row.id), lifecycleStatus, isAssignable:lifecycleStatus!=="expired" }; };
const encode = (value:any, fields:string[]) => ({ ...value, ...Object.fromEntries(fields.map(k=>[k,JSON.stringify(value[k]??[])])) });

for (const [path, config] of Object.entries(configs)) {
  const list = async (req:any,res:any,admin=false) => { const org=organizationId(req); const rows=await db.select().from(config.table).where(eq(config.table.organizationId,org)).orderBy(asc(config.table.templateName)); const visible=admin?rows:rows.filter((r:any)=>r.isActive!==false); return res.json(visible.map((r:any)=>decode(r,config.json)).sort((a:any,b:any)=>Number(b.isDefault)-Number(a.isDefault)||a.templateName.localeCompare(b.templateName))); };
  router.get(`/${path}`, requirePermission("settings.templates.view"), (req,res)=>list(req,res));
  router.get(`/${path}/admin`, requirePermission("settings.templates.view"), (req,res)=>list(req,res,true));
  router.post(`/${path}`, requirePermission("settings.templates.create"), async (req,res)=>{ const parsed=config.schema.safeParse(req.body); if(!parsed.success)return res.status(400).json({error:z.prettifyError(parsed.error)}); const org=organizationId(req), value:any=parsed.data; const rows=await db.select().from(config.table).where(eq(config.table.organizationId,org)); if(rows.some((r:any)=>r.isActive!==false&&r.templateName.trim().toLowerCase()===value.templateName.toLowerCase()))return res.status(400).json({error:"An active template with this name already exists"}); const created=await db.transaction(async tx=>{if(value.isDefault)await tx.update(config.table).set({isDefault:false,updatedAt:new Date()}).where(eq(config.table.organizationId,org)); const [row]=await tx.insert(config.table).values({...encode(value,config.json),organizationId:org,isActive:true,updatedAt:new Date()}).returning(); return row;}); return res.status(201).json(decode(created,config.json)); });
  router.put(`/${path}/:id`, requirePermission("settings.templates.update"), async (req,res)=>{ const parsed=config.schema.safeParse(req.body); if(!parsed.success)return res.status(400).json({error:z.prettifyError(parsed.error)}); const org=organizationId(req), id=Number(req.params.id), value:any=parsed.data; const [existing]=await db.select().from(config.table).where(and(eq(config.table.id,id),eq(config.table.organizationId,org))); if(!existing)return res.status(404).json({error:"Template not found"}); const rows=await db.select().from(config.table).where(eq(config.table.organizationId,org)); if(rows.some((r:any)=>r.id!==id&&r.isActive!==false&&r.templateName.trim().toLowerCase()===value.templateName.toLowerCase()))return res.status(400).json({error:"An active template with this name already exists"}); const updated=await db.transaction(async tx=>{if(value.isDefault)await tx.update(config.table).set({isDefault:false,updatedAt:new Date()}).where(eq(config.table.organizationId,org)); const [row]=await tx.update(config.table).set({...encode(value,config.json),updatedAt:new Date()}).where(and(eq(config.table.id,id),eq(config.table.organizationId,org))).returning(); return row;}); return res.json(decode(updated,config.json)); });
  router.delete(`/${path}/:id`, requirePermission("settings.templates.delete"), async (req,res)=>{ const org=organizationId(req),id=Number(req.params.id); const [row]=await db.update(config.table).set({isActive:false,isDefault:false,updatedAt:new Date()}).where(and(eq(config.table.id,id),eq(config.table.organizationId,org))).returning(); if(!row)return res.status(404).json({error:"Template not found"}); if(config.ensureDefault){const active=(await db.select().from(config.table).where(eq(config.table.organizationId,org))).filter((r:any)=>r.isActive!==false);if(active.length&&!active.some((r:any)=>r.isDefault))await db.update(config.table).set({isDefault:true,updatedAt:new Date()}).where(eq(config.table.id,active[0].id));} return res.status(204).send(); });
}

router.post("/holiday-templates/:id/duplicate", requirePermission("settings.templates.create"), async (req,res)=>{const org=organizationId(req),[source]=await db.select().from(holidayTemplatesTable).where(and(eq(holidayTemplatesTable.id,Number(req.params.id)),eq(holidayTemplatesTable.organizationId,org)));if(!source||source.isActive===false)return res.status(404).json({error:"Template not found"});const rows=await db.select().from(holidayTemplatesTable).where(eq(holidayTemplatesTable.organizationId,org));let name=`${source.templateName} Copy`,i=2;while(rows.some((r:any)=>r.isActive!==false&&r.templateName.toLowerCase()===name.toLowerCase()))name=`${source.templateName} Copy ${i++}`;const [created]=await db.insert(holidayTemplatesTable).values({...source,id:undefined,templateName:name,isDefault:false,createdAt:new Date(),updatedAt:new Date()}).returning();return res.status(201).json(decode(created,["holidays"]));});
router.get("/holiday-templates/google-holidays", requirePermission("settings.templates.view"), async (req,res)=>{const year=Number(req.query.year);if(!Number.isInteger(year)||year<1970||year>3000)return res.status(400).json({error:"Valid year is required"});return res.json({holidays:[],source:"manual",timeZone:"Asia/Kolkata",calendarId:"en.indian#holiday@group.v.calendar.google.com",message:"Google Calendar credentials are not configured"});});

export default router;
