import { useState } from "react";
import { ChevronDown, ChevronRight, MapPin, Palette, Settings as SettingsIcon, ShieldCheck, Users } from "lucide-react";
import { Shell } from "@/components/layout/Shell";
import UserManagement from "./user-management";
import TemplateManager from "./templates";
import Locations from "./locations";
import AlertColors from "./alert-colors";
import { useAuth } from "@/lib/auth";

type View="general"|"users"|"attendance"|"work-pattern"|"salary"|"holiday"|"leave"|"alerts"|"locations";
const templates:[View,string][]=[["attendance","Attendance Template"],["work-pattern","Work Pattern Template"],["salary","Salary Template"],["holiday","Holiday Template"],["leave","Leave Template"]];
export default function Settings(){const {can}=useAuth();const userAccess=can("settings.user_management.view"),templateAccess=can("settings.templates.view");const [view,setView]=useState<View>(userAccess?"users":"attendance"),[expanded,setExpanded]=useState(true);return <Shell><div className="min-h-[calc(100vh-72px)] w-full bg-muted/30 p-5 md:p-7"><div className="mb-6"><h1 className="text-2xl font-bold tracking-tight">System Settings</h1><p className="text-sm text-muted-foreground">Manage users, roles, templates, and system configuration.</p></div><div className="grid items-start gap-6 md:grid-cols-[280px_minmax(0,1fr)]"><nav className="sticky top-[96px] h-fit min-w-0 p-1">{userAccess&&<><Nav active={view==="general"} onClick={()=>setView("general")} icon={<SettingsIcon/>}>General</Nav><Nav active={view==="users"} onClick={()=>setView("users")} icon={<Users/>}>User Management</Nav></>}{templateAccess&&<><button className="flex w-full items-center gap-3 rounded-md px-4 py-3 text-sm hover:bg-background/70" onClick={()=>setExpanded(!expanded)}>{expanded?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}<ShieldCheck className="h-4 w-4"/>Templates</button>{expanded&&<div className="ml-7 border-l pl-2">{templates.map(([key,label])=><button key={key} onClick={()=>setView(key)} className={`block w-full rounded-md px-3 py-2.5 text-left text-sm ${view===key?"bg-primary/10 font-medium text-primary":"text-muted-foreground hover:bg-background/70"}`}>{label}</button>)}</div>}</>}{userAccess&&<><Nav active={view==="alerts"} onClick={()=>setView("alerts")} icon={<Palette/>}>Alert Colors</Nav><Nav active={view==="locations"} onClick={()=>setView("locations")} icon={<MapPin/>}>Locations</Nav></>}</nav><section className="min-w-0 rounded-xl border bg-card p-5 shadow-sm md:p-7">{view==="general"&&<div><h2 className="text-xl font-semibold">General Settings</h2><p className="mt-2 text-sm text-muted-foreground">Organization-wide preferences and configuration.</p></div>}{view==="users"&&userAccess&&<UserManagement/>}{templates.some(([k])=>k===view)&&templateAccess&&<TemplateManager kind={view as any}/>} {view==="alerts"&&<AlertColors/>}{view==="locations"&&<Locations/>}</section></div></div></Shell>}
function Nav({active,onClick,icon,children}:{active:boolean;onClick:()=>void;icon:any;children:any}){return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-md px-4 py-3 text-sm ${active?"bg-primary/10 font-medium text-primary":"hover:bg-background/70"}`}><span className="[&>svg]:h-4 [&>svg]:w-4">{icon}</span>{children}</button>}
