import { useEffect, useMemo, useState } from "react";
import { Edit2, Plus, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

const BASE=import.meta.env.BASE_URL?.replace(/\/$/,"")??"";
type Role={id:number;name:string;description?:string;permissions:string[]|Record<string,string[]>;isSystem:boolean;isSuperAdmin?:boolean;systemKey?:string};
type Catalog={module:string;key:string;actions:string[]};
async function request(path:string,options?:RequestInit){const r=await fetch(`${BASE}/api/settings/${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(options?.headers||{})},...options});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||"Request failed")}return r.status===204?null:r.json()}
export default function RolesPage(){const {toast}=useToast();const [roles,setRoles]=useState<Role[]>([]),[catalog,setCatalog]=useState<Catalog[]>([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<Role|null>(null),[name,setName]=useState(""),[description,setDescription]=useState(""),[permissions,setPermissions]=useState<string[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [r,c]=await Promise.all([request("roles"),request("permissions/catalog")]);setRoles(r);setCatalog(c)}catch(e:any){toast({title:"Unable to load roles",description:e.message,variant:"destructive"})}};useEffect(()=>{void load()},[]);
 const shown=useMemo(()=>roles.filter(r=>!r.isSuperAdmin&&r.name!=="admin"&&`${r.name} ${r.description||""}`.toLowerCase().includes(search.toLowerCase())),[roles,search]);
 const begin=(r?:Role)=>{setEditing(r||null);setName(r?.name||"");setDescription(r?.description||"");setPermissions(Array.isArray(r?.permissions)?r!.permissions:[]);setOpen(true)};
 const toggle=(key:string,checked:boolean)=>{const [scope,action]=key.split(/\.(?=[^.]+$)/);setPermissions(current=>{let next=checked?[...new Set([...current,key])]:current.filter(k=>k!==key);if(checked&&action!=="view")next=[...new Set([...next,`${scope}.view`])];if(!checked&&action==="view")next=next.filter(k=>!k.startsWith(`${scope}.`));return next})};
 const save=async()=>{setBusy(true);try{await request(editing?`roles/${editing.id}`:"roles",{method:editing?"PATCH":"POST",body:JSON.stringify({name,description,permissions})});setOpen(false);await load();toast({title:`Role ${editing?"updated":"created"}`})}catch(e:any){toast({title:"Unable to save role",description:e.message,variant:"destructive"})}finally{setBusy(false)}};
 return <div className="space-y-4"><div className="flex items-center justify-between gap-3"><Input className="max-w-sm" placeholder="Search roles…" value={search} onChange={e=>setSearch(e.target.value)}/><Button onClick={()=>begin()}><Plus className="mr-2 h-4 w-4"/>New Role</Button></div><div className="grid gap-3 md:grid-cols-2">{shown.map(r=>{const p=Array.isArray(r.permissions)?r.permissions:[];return <div key={r.id} className="rounded-lg border p-4"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{r.name}</h3>{r.isSystem&&<Badge variant="secondary">System</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">{r.description||"No description"}</p></div>{!r.isSystem&&!r.systemKey&&<Button size="icon" variant="ghost" onClick={()=>begin(r)}><Edit2 className="h-4 w-4"/></Button>}</div><div className="mt-4 flex gap-5 text-xs text-muted-foreground"><span>{new Set(p.map(k=>k.split('.')[0])).size} enabled modules</span><span>{p.length} permissions</span></div></div>})}</div>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Edit Role":"New Role"}</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><div><Label>Role name</Label><Input disabled={!!editing} value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Description</Label><Textarea value={description} onChange={e=>setDescription(e.target.value)}/></div></div><div className="mt-4 overflow-x-auto rounded-lg border"><div className="grid grid-cols-[220px_repeat(5,minmax(80px,1fr))] border-b bg-muted/40 px-3 py-2 text-xs font-medium uppercase text-muted-foreground"><span>Module</span><span>View</span><span>Create</span><span>Update</span><span>Delete</span><span>Other</span></div>{catalog.map(row=><div key={row.key} className="grid grid-cols-[220px_repeat(5,minmax(80px,1fr))] items-center border-b px-3 py-3 text-sm last:border-0"><span className="font-medium">{row.module}</span>{["view","create","update","delete"].map(action=><span key={action}>{row.actions.includes(action)?<Checkbox checked={permissions.includes(`${row.key}.${action}`)} onCheckedChange={v=>toggle(`${row.key}.${action}`,v===true)}/>:"—"}</span>)}<div className="flex flex-wrap gap-2">{row.actions.filter(a=>!["view","create","update","delete"].includes(a)).map(action=><label key={action} className="flex items-center gap-1 text-xs"><Checkbox checked={permissions.includes(`${row.key}.${action}`)} onCheckedChange={v=>toggle(`${row.key}.${action}`,v===true)}/>{action.replace('_',' ')}</label>)}</div></div>)}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||!name.trim()} onClick={()=>void save()}><ShieldCheck className="mr-2 h-4 w-4"/>{busy?"Saving…":"Save Role"}</Button></DialogFooter></DialogContent></Dialog></div>}
