import { useEffect, useMemo, useState } from "react";
import { Edit2, Plus, Star, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";

const BASE = import.meta.env.BASE_URL?.replace(/\/$/, "") ?? "";
type Kind="attendance"|"work-pattern"|"salary"|"holiday"|"leave";
type Props={kind:Kind};
const info:Record<Kind,{title:string;route:string;description:string}>={
 attendance:{title:"Attendance Templates",route:"attendance-templates",description:"Working hours, late tolerance, and attendance fines."},
 "work-pattern":{title:"Work Pattern Templates",route:"work-pattern-templates",description:"Weekly off-day patterns for weeks one through five."},
 salary:{title:"Salary Templates",route:"salary-templates",description:"Reusable salary component calculation formulas."},
 holiday:{title:"Holiday Templates",route:"holiday-templates",description:"Effective-year holiday calendars and lifecycle rules."},
 leave:{title:"Leave Templates",route:"leave-templates",description:"Annual leave entitlements and monthly usage limits."},
};
const weekdays=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const defaults=(kind:Kind):any=>kind==="attendance"?{templateName:"",isDefault:false,flexibleHours:false,lateThresholdMinutes:15,workStartTime:"09:00",workEndTime:"17:00",fineType:"fixed_per_hour",finePerHour:0}:kind==="work-pattern"?{templateName:"",isDefault:false,week1OffDays:[0],week2OffDays:[0],week3OffDays:[0],week4OffDays:[0],week5OffDays:[0]}:kind==="salary"?{templateName:"",isDefault:false,description:"",components:[{id:"basic",name:"Basic",calculationType:"percentage_of_ctc",value:"40",referenceComponentId:null,order:1}]}:kind==="holiday"?{templateName:"",isDefault:false,effectiveYear:new Date().getFullYear()+1,effectiveFrom:`${new Date().getFullYear()+1}-01-01`,holidays:[]}:{templateName:"",isDefault:false,totalSickLeaves:0,totalCasualLeaves:0,earnedLeave:0,maxSickLeavesPerMonth:0,maxCasualLeavesPerMonth:0,maxEarnedLeavesPerMonth:0,carryForwardEnabled:true};
async function request(path:string,options?:RequestInit){const res=await fetch(`${BASE}/api/${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(options?.headers||{})},...options});if(!res.ok){const body=await res.json().catch(()=>({}));throw new Error(body.error||"Request failed");}return res.status===204?null:res.json();}

export default function TemplateManager({kind}:Props){const meta=info[kind],{toast}=useToast();const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[editing,setEditing]=useState<any>(null),[form,setForm]=useState<any>(defaults(kind)),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{setRows(await request(`${meta.route}/admin`));}catch(e:any){toast({title:"Unable to load templates",description:e.message,variant:"destructive"});}finally{setLoading(false)}};
 useEffect(()=>{void load()},[kind]);
 const begin=(row?:any)=>{setEditing(row||null);setForm(row?JSON.parse(JSON.stringify(row)):defaults(kind));setOpen(true)};
 const set=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
 const save=async()=>{setSaving(true);try{await request(`${meta.route}${editing?`/${editing.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify(form)});toast({title:`Template ${editing?"updated":"created"}`});setOpen(false);await load()}catch(e:any){toast({title:"Unable to save",description:e.message,variant:"destructive"})}finally{setSaving(false)}};
 const remove=async(row:any)=>{if(!window.confirm(`Deactivate “${row.templateName}”?`))return;try{await request(`${meta.route}/${row.id}`,{method:"DELETE"});toast({title:"Template deactivated"});await load()}catch(e:any){toast({title:"Unable to delete",description:e.message,variant:"destructive"})}};
 const active=useMemo(()=>rows.filter(r=>r.isActive!==false),[rows]);
 return <div className="space-y-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{meta.title}</h2><p className="text-sm text-muted-foreground">{meta.description}</p></div><Button onClick={()=>begin()}><Plus className="mr-2 h-4 w-4"/>Create Template</Button></div>
 {loading?<p className="py-12 text-center text-sm text-muted-foreground">Loading templates…</p>:active.length===0?<div className="rounded-lg border border-dashed p-12 text-center"><p className="font-medium">No active templates</p><p className="mt-1 text-sm text-muted-foreground">Create the first template for your organization.</p></div>:<div className="grid gap-3 lg:grid-cols-2">{active.map(row=><Card key={row.id}><CardContent className="p-5"><div className="flex justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate font-semibold">{row.templateName}</h3>{row.isDefault&&<span className="flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-[11px] text-primary"><Star className="h-3 w-3 fill-current"/>Default</span>}</div><p className="mt-2 text-sm text-muted-foreground">{summary(kind,row)}</p></div><div className="flex shrink-0"><Button size="icon" variant="ghost" onClick={()=>begin(row)} aria-label="Edit"><Edit2 className="h-4 w-4"/></Button><Button size="icon" variant="ghost" className="text-destructive" onClick={()=>void remove(row)} aria-label="Delete"><Trash2 className="h-4 w-4"/></Button></div></div></CardContent></Card>)}</div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Edit":"Create"} {meta.title.replace(/s$/,'')}</DialogTitle></DialogHeader><div className="space-y-5 py-2"><Field label="Template name"><Input maxLength={120} value={form.templateName} onChange={e=>set("templateName",e.target.value)}/></Field><label className="flex items-center gap-2 text-sm"><Checkbox checked={form.isDefault} onCheckedChange={v=>set("isDefault",v===true)}/>Mark as organization default</label>{fields(kind,form,set)}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving||!form.templateName?.trim()} onClick={()=>void save()}>{saving?"Saving…":"Save Template"}</Button></DialogFooter></DialogContent></Dialog></div>;
}
function Field({label,children}:{label:string;children:any}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function fields(kind:Kind,f:any,set:(k:string,v:any)=>void){if(kind==="attendance")return <div className="grid gap-4 sm:grid-cols-2"><Field label="Work start"><Input type="time" value={f.workStartTime} onChange={e=>set("workStartTime",e.target.value)}/></Field><Field label="Work end"><Input type="time" value={f.workEndTime} onChange={e=>set("workEndTime",e.target.value)}/></Field><Field label="Late threshold (minutes)"><Input type="number" min="0" value={f.lateThresholdMinutes} onChange={e=>set("lateThresholdMinutes",Number(e.target.value))}/></Field><Field label="Fine per hour"><Input type="number" min="0" step="0.01" value={f.finePerHour} onChange={e=>set("finePerHour",Number(e.target.value))}/></Field><Field label="Fine type"><select className="flex h-10 w-full rounded-md border bg-background px-3 text-sm" value={f.fineType} onChange={e=>set("fineType",e.target.value)}><option value="fixed_per_hour">Fixed per hour</option><option value="percent_hourly_basis">Percentage of hourly basis</option></select></Field><label className="flex items-center gap-2 pt-7 text-sm"><Checkbox checked={f.flexibleHours} onCheckedChange={v=>set("flexibleHours",v===true)}/>Flexible hours</label></div>;
 if(kind==="work-pattern")return <div className="space-y-4">{[1,2,3,4,5].map(w=>{const key=`week${w}OffDays`,selected=f[key]||[];return <Field key={key} label={`Week ${w} off-days`}><div className="flex flex-wrap gap-2">{weekdays.map((d,i)=><Button key={d} type="button" size="sm" variant={selected.includes(i)?"default":"outline"} onClick={()=>set(key,selected.includes(i)?selected.filter((x:number)=>x!==i):[...selected,i].sort())}>{d}</Button>)}</div></Field>})}</div>;
 if(kind==="salary")return <div className="space-y-4"><Field label="Description"><Textarea value={f.description||""} onChange={e=>set("description",e.target.value)}/></Field><div className="space-y-3"><div className="flex justify-between"><Label>Components</Label><Button type="button" size="sm" variant="outline" onClick={()=>set("components",[...f.components,{id:`component_${f.components.length+1}`,name:"Component",calculationType:"fixed",value:"0",referenceComponentId:null,order:f.components.length+1}])}>Add component</Button></div>{f.components.map((c:any,i:number)=><div key={i} className="grid gap-2 rounded border p-3 sm:grid-cols-4"><Input value={c.id} placeholder="Key" onChange={e=>set("components",f.components.map((x:any,j:number)=>j===i?{...x,id:e.target.value,name:e.target.value}:x))}/><select className="h-10 rounded-md border bg-background px-2 text-sm" value={c.calculationType} onChange={e=>set("components",f.components.map((x:any,j:number)=>j===i?{...x,calculationType:e.target.value}:x))}><option value="fixed">Fixed</option><option value="percentage_of_ctc">% of CTC</option><option value="percentage_of_component">% of component</option><option value="residual">Residual</option></select><Input value={c.value??""} disabled={c.calculationType==="residual"} placeholder="Value" onChange={e=>set("components",f.components.map((x:any,j:number)=>j===i?{...x,value:e.target.value}:x))}/><Button type="button" variant="ghost" className="text-destructive" onClick={()=>set("components",f.components.filter((_:any,j:number)=>j!==i).map((x:any,j:number)=>({...x,order:j+1})))}>Remove</Button>{c.calculationType==="percentage_of_component"&&<Input className="sm:col-span-4" value={c.referenceComponentId||""} placeholder="Reference component key" onChange={e=>set("components",f.components.map((x:any,j:number)=>j===i?{...x,referenceComponentId:e.target.value}:x))}/>}</div>)}</div></div>;
 if(kind==="holiday")return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Effective year"><Input type="number" min="1970" max="3000" value={f.effectiveYear} onChange={e=>{const y=Number(e.target.value);set("effectiveYear",y);set("effectiveFrom",`${y}-01-01`)}}/></Field><Field label="Effective from"><Input type="date" value={f.effectiveFrom} onChange={e=>set("effectiveFrom",e.target.value)}/></Field></div><div className="space-y-3"><div className="flex justify-between"><Label>Holidays</Label><Button type="button" size="sm" variant="outline" onClick={()=>set("holidays",[...f.holidays,{name:"",date:`${f.effectiveYear}-01-01`}])}>Add holiday</Button></div>{f.holidays.map((h:any,i:number)=><div key={i} className="flex gap-2"><Input value={h.name} placeholder="Holiday name" onChange={e=>set("holidays",f.holidays.map((x:any,j:number)=>j===i?{...x,name:e.target.value}:x))}/><Input type="date" value={h.date} onChange={e=>set("holidays",f.holidays.map((x:any,j:number)=>j===i?{...x,date:e.target.value}:x))}/><Button type="button" variant="ghost" className="text-destructive" onClick={()=>set("holidays",f.holidays.filter((_:any,j:number)=>j!==i))}><Trash2 className="h-4 w-4"/></Button></div>)}</div></div>;
 const nums=[['totalSickLeaves','Total sick leaves'],['totalCasualLeaves','Total casual leaves'],['earnedLeave','Earned leave'],['maxSickLeavesPerMonth','Max sick/month'],['maxCasualLeavesPerMonth','Max casual/month'],['maxEarnedLeavesPerMonth','Max earned/month']];return <div className="grid gap-4 sm:grid-cols-2">{nums.map(([k,l])=><Field key={k} label={l}><Input type="number" min="0" value={f[k]} onChange={e=>set(k,Number(e.target.value))}/></Field>)}<p className="sm:col-span-2 text-sm text-muted-foreground">Carry-forward policy: Full balance carry forward is enabled.</p></div>;
}
function summary(kind:Kind,r:any){if(kind==="attendance")return `${r.workStartTime} – ${r.workEndTime} • Late threshold ${r.lateThresholdMinutes} mins • ${r.fineType==="fixed_per_hour"?"INR":"%"} ${Number(r.finePerHour).toFixed(2)}/hour`;if(kind==="work-pattern")return [1,2,3,4,5].map(w=>`W${w}: ${(r[`week${w}OffDays`]||[]).map((d:number)=>weekdays[d]).join(', ')||'No week off'}`).join(" • ");if(kind==="salary")return `${r.components?.length||0} salary component(s)${r.description?` • ${r.description}`:""}`;if(kind==="holiday")return `${r.effectiveYear} • Effective ${r.effectiveFrom} • ${r.holidays?.length||0} holidays • ${r.lifecycleStatus||"active"}`;return `${r.totalSickLeaves} sick • ${r.totalCasualLeaves} casual • ${r.earnedLeave} earned days`;}
