import { useEffect, useMemo, useState } from "react";
import { Copy, Edit2, Plus, RefreshCw, Star, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";
import { SalaryTemplateFields } from "./SalaryTemplateFields";

const BASE = import.meta.env.BASE_URL?.replace(/\/$/, "") ?? "";
type Kind="attendance"|"work-pattern"|"salary"|"holiday"|"leave";
type Props={kind:Kind};
const info:Record<Kind,{title:string;route:string;description:string}>={
 attendance:{title:"Attendance Templates",route:"attendance-templates",description:"Working hours, late tolerance, and attendance fines."},
 "work-pattern":{title:"Work Pattern Templates",route:"work-pattern-templates",description:"Weekly off-day patterns for weeks one through five."},
 salary:{title:"Salary Templates",route:"salary-templates",description:"Reusable salary component calculation formulas."},
 holiday:{title:"Holiday Templates",route:"holiday-templates",description:"Effective-year holiday calendars and lifecycle rules."},
 leave:{title:"Leave Templates",route:"leave-templates",description:"Annual leave entitlements and monthly usage limits."},
};
const weekdays=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const defaults=(kind:Kind):any=>kind==="attendance"?{templateName:"",isDefault:false,flexibleHours:false,lateThresholdMinutes:15,workStartTime:"09:00",workEndTime:"17:00",fineType:"fixed_per_hour",finePerHour:0}:kind==="work-pattern"?{templateName:"",isDefault:false,week1OffDays:[0],week2OffDays:[0],week3OffDays:[0],week4OffDays:[0],week5OffDays:[0]}:kind==="salary"?{templateName:"",isDefault:false,description:"",components:[{id:"basic",name:"Basic",calculationType:"fixed",value:"",referenceComponentId:null,order:1}]}:kind==="holiday"?{templateName:"",isDefault:false,effectiveYear:new Date().getFullYear()+1,effectiveFrom:`${new Date().getFullYear()+1}-01-01`,holidays:[]}:{templateName:"",isDefault:false,totalSickLeaves:6,totalCasualLeaves:6,earnedLeave:0,maxSickLeavesPerMonth:6,maxCasualLeavesPerMonth:6,maxEarnedLeavesPerMonth:0,carryForwardEnabled:true};
async function request(path:string,options?:RequestInit){const res=await fetch(`${BASE}/api/${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(options?.headers||{})},...options});if(!res.ok){const body=await res.json().catch(()=>({}));throw new Error(body.error||"Request failed");}return res.status===204?null:res.json();}

export default function TemplateManager({kind}:Props){const meta=info[kind],{toast}=useToast();const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[editing,setEditing]=useState<any>(null),[form,setForm]=useState<any>(defaults(kind)),[saving,setSaving]=useState(false),[fetchingHolidays,setFetchingHolidays]=useState(false);
 const load=async()=>{setLoading(true);try{setRows(await request(`${meta.route}/admin`));}catch(e:any){toast({title:"Unable to load templates",description:e.message,variant:"destructive"});}finally{setLoading(false)}};
 useEffect(()=>{setOpen(false);setEditing(null);setForm(defaults(kind));void load()},[kind]);
 const begin=(row?:any)=>{setEditing(row||null);setForm(row?{...defaults(kind),...JSON.parse(JSON.stringify(row))}:defaults(kind));setOpen(true)};
 const set=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
 const save=async()=>{if(kind==="salary"){const components=form.components||[],ids=components.map((c:any)=>c.id.trim());if(!components.length){toast({title:"Add at least one salary component",variant:"destructive"});return;}if(ids.some((id:string)=>!id)||new Set(ids).size!==ids.length){toast({title:"Component IDs must be filled and unique",variant:"destructive"});return;}for(const c of components){const n=Number(c.value);if(!c.name?.trim()){toast({title:"Every component needs a name",variant:"destructive"});return;}if(c.calculationType!=="residual"&&(!Number.isFinite(n)||n<0)){toast({title:`Enter a valid value for ${c.name}`,variant:"destructive"});return;}if(c.calculationType.startsWith("percentage")&&n>100){toast({title:`${c.name} percentage cannot exceed 100`,variant:"destructive"});return;}if(c.calculationType==="percentage_of_component"&&(!c.referenceComponentId||!ids.includes(c.referenceComponentId)||c.referenceComponentId===c.id)){toast({title:`Select another valid reference for ${c.name}`,variant:"destructive"});return;}}}setSaving(true);try{await request(`${meta.route}${editing?`/${editing.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify(form)});toast({title:`Template ${editing?"updated":"created"}`});setOpen(false);await load()}catch(e:any){toast({title:"Unable to save",description:e.message,variant:"destructive"})}finally{setSaving(false)}};
 const fetchHolidays=async()=>{setFetchingHolidays(true);try{const data=await request(`holiday-templates/google-holidays?year=${form.effectiveYear}`);set("holidays",data.holidays||[]);toast({title:`Imported ${data.holidays?.length||0} holidays`,description:`Calendar: ${data.calendarId}`})}catch(e:any){toast({title:"Unable to fetch Google holidays",description:e.message,variant:"destructive"})}finally{setFetchingHolidays(false)}}; const duplicate=async(row:any)=>{try{await request(`holiday-templates/${row.id}/duplicate`,{method:"POST"});toast({title:"Holiday template duplicated"});await load()}catch(e:any){toast({title:"Unable to duplicate",description:e.message,variant:"destructive"})}}; const remove=async(row:any)=>{if(!window.confirm(`Deactivate “${row.templateName}”?`))return;try{await request(`${meta.route}/${row.id}`,{method:"DELETE"});toast({title:"Template deactivated"});await load()}catch(e:any){toast({title:"Unable to delete",description:e.message,variant:"destructive"})}};
 const active=useMemo(()=>rows.filter(r=>r.isActive!==false),[rows]);
 return <div className="space-y-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{meta.title}</h2></div><Button onClick={()=>begin()}><Plus className="mr-2 h-4 w-4"/>Create Template</Button></div>
 {loading?<p className="py-12 text-center text-sm text-muted-foreground">Loading templates…</p>:active.length===0?<div className="rounded-lg border border-dashed p-12 text-center"><p className="font-medium">No active templates</p><p className="mt-1 text-sm text-muted-foreground">Create the first template for your organization.</p></div>:<div className="grid gap-3 lg:grid-cols-2">{active.map(row=><Card key={row.id}><CardContent className="p-5"><div className="flex justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate font-semibold">{row.templateName}</h3>{row.isDefault&&<span className="flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-[11px] text-primary"><Star className="h-3 w-3 fill-current"/>Default</span>}</div><p className="mt-2 text-sm text-muted-foreground">{summary(kind,row)}</p></div><div className="flex shrink-0">{kind==="holiday"&&<Button size="icon" variant="ghost" onClick={()=>void duplicate(row)} aria-label="Duplicate"><Copy className="h-4 w-4"/></Button>}<Button size="icon" variant="ghost" onClick={()=>begin(row)} aria-label="Edit"><Edit2 className="h-4 w-4"/></Button><Button size="icon" variant="ghost" className="text-destructive" onClick={()=>void remove(row)} aria-label="Delete"><Trash2 className="h-4 w-4"/></Button></div></div></CardContent></Card>)}</div>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className={`max-h-[90vh] overflow-y-auto ${kind==="salary"?"max-w-4xl":kind==="holiday"?"max-w-3xl":"max-w-2xl"}`}><DialogHeader><DialogTitle>{editing?"Edit":"Create"} {meta.title.replace(/s$/,'')}</DialogTitle></DialogHeader><div className="space-y-5 py-2"><div className="grid items-end gap-4 sm:grid-cols-[minmax(0,1fr)_auto]"><Field label="Template name"><Input maxLength={120} placeholder="e.g., Standard Salary Structure" value={form.templateName} onChange={e=>set("templateName",e.target.value)}/></Field><label className="flex h-10 items-center gap-2 px-1 text-sm"><Checkbox checked={form.isDefault} onCheckedChange={v=>set("isDefault",v===true)}/>Default</label></div>{fields(kind,form,set,fetchHolidays,fetchingHolidays)}</div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving||!form.templateName?.trim()} onClick={()=>void save()}>{saving?"Saving�":editing?"Save Changes":"Create Template"}</Button></DialogFooter></DialogContent></Dialog></div>;
}
function Field({label,children}:{label:string;children:any}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function fields(kind:Kind,f:any,set:(k:string,v:any)=>void,fetchHolidays:()=>Promise<void>,fetchingHolidays:boolean){if(kind==="attendance")return <div className="grid gap-4 sm:grid-cols-2"><Field label="Work start"><Input type="time" value={f.workStartTime} onChange={e=>set("workStartTime",e.target.value)}/></Field><Field label="Work end"><Input type="time" value={f.workEndTime} onChange={e=>set("workEndTime",e.target.value)}/></Field><Field label="Late threshold (minutes)"><Input type="number" min="0" value={f.lateThresholdMinutes} onChange={e=>set("lateThresholdMinutes",Number(e.target.value))}/></Field><Field label="Fine per hour"><Input type="number" min="0" step="0.01" value={f.finePerHour} onChange={e=>set("finePerHour",Number(e.target.value))}/></Field><Field label="Fine type"><select className="flex h-10 w-full rounded-md border bg-background px-3 text-sm" value={f.fineType} onChange={e=>set("fineType",e.target.value)}><option value="fixed_per_hour">Fixed per hour</option><option value="percent_hourly_basis">Percentage of hourly basis</option></select></Field><label className="flex items-center gap-2 pt-7 text-sm"><Checkbox checked={f.flexibleHours} onCheckedChange={v=>set("flexibleHours",v===true)}/>Flexible hours</label></div>;
 if(kind==="work-pattern")return <div className="space-y-4">{[1,2,3,4,5].map(w=>{const key=`week${w}OffDays`,selected=f[key]||[];return <Field key={key} label={`Week ${w} off-days`}><div className="flex flex-wrap gap-2">{weekdays.map((d,i)=><Button key={d} type="button" size="sm" variant={selected.includes(i)?"default":"outline"} onClick={()=>set(key,selected.includes(i)?selected.filter((x:number)=>x!==i):[...selected,i].sort())}>{d}</Button>)}</div></Field>})}</div>;
 if(kind==="salary")return <SalaryTemplateFields form={f} set={set}/>;
 if(kind==="holiday")return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><Field label="Effective year"><Input type="number" min="1970" max="3000" value={f.effectiveYear} onChange={e=>{const y=Number(e.target.value);set("effectiveYear",y);set("effectiveFrom",`${y}-01-01`)}}/></Field><Field label="Effective from"><Input type="date" value={f.effectiveFrom} onChange={e=>set("effectiveFrom",e.target.value)}/></Field><div className="flex items-end"><Button type="button" variant="outline" className="w-full border-primary text-primary" disabled={fetchingHolidays} onClick={()=>void fetchHolidays()}>{fetchingHolidays?<RefreshCw className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}Fetch Google Holidays</Button></div></div><div className="space-y-3 rounded-md border bg-muted/20 p-4"><div className="flex items-center justify-between"><div><Label>Holiday checklist</Label><p className="text-xs text-muted-foreground">{(f.holidays||[]).length} holidays</p></div><Button type="button" size="sm" variant="outline" onClick={()=>set("holidays",[...(f.holidays||[]),{name:"",date:`${f.effectiveYear}-01-01`}])}><Plus className="mr-1 h-4 w-4"/>Add Holiday</Button></div>{(f.holidays||[]).map((h:any,i:number)=><div key={i} className="flex gap-2"><Input value={h.name} placeholder="Holiday name" onChange={e=>set("holidays",f.holidays.map((x:any,j:number)=>j===i?{...x,name:e.target.value}:x))}/><Input type="date" value={h.date} onChange={e=>set("holidays",f.holidays.map((x:any,j:number)=>j===i?{...x,date:e.target.value}:x))}/><Button type="button" variant="ghost" className="text-destructive" onClick={()=>set("holidays",f.holidays.filter((_:any,j:number)=>j!==i))}><Trash2 className="h-4 w-4"/></Button></div>)}</div></div>;
 const nums=[['totalSickLeaves','Total sick leaves'],['totalCasualLeaves','Total casual leaves'],['maxSickLeavesPerMonth','Maximum sick leaves / month'],['maxCasualLeavesPerMonth','Maximum casual leaves / month']];return <div className="grid gap-4 sm:grid-cols-2">{nums.map(([k,l])=><Field key={k} label={l}><Input type="number" min="0" value={f[k]} onChange={e=>set(k,Number(e.target.value))}/></Field>)}<label className="flex items-center gap-2 text-sm sm:col-span-2"><Checkbox checked={f.carryForwardEnabled} onCheckedChange={v=>set("carryForwardEnabled",v===true)}/>Enable unused leave carry-forward</label></div>;
}
function summary(kind:Kind,r:any){if(kind==="attendance")return `${r.workStartTime} – ${r.workEndTime} • Late threshold ${r.lateThresholdMinutes} mins • ${r.fineType==="fixed_per_hour"?"INR":"%"} ${Number(r.finePerHour).toFixed(2)}/hour`;if(kind==="work-pattern")return [1,2,3,4,5].map(w=>`W${w}: ${(r[`week${w}OffDays`]||[]).map((d:number)=>weekdays[d]).join(', ')||'No week off'}`).join(" • ");if(kind==="salary")return `${r.components?.length||0} salary component(s)${r.description?` • ${r.description}`:""}`;if(kind==="holiday")return `${r.effectiveYear} • Effective ${r.effectiveFrom} • ${r.holidays?.length||0} holidays • ${r.lifecycleStatus||"active"}`;return `${r.totalSickLeaves} sick • ${r.totalCasualLeaves} casual • ${r.earnedLeave} earned days`;}
