import { useEffect, useMemo, useState } from "react";
import { Edit2, KeyRound, Plus, RefreshCw, Search, UserX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import RolesPage from "./roles";

const BASE=import.meta.env.BASE_URL?.replace(/\/$/,"")??"";
async function api(path:string,options?:RequestInit){const r=await fetch(`${BASE}/api/settings/users${path}`,{credentials:"include",headers:{"Content-Type":"application/json",...(options?.headers||{})},...options});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||"Request failed")}return r.status===204?null:r.json()}
type User={id:number;displayName:string;username:string;email?:string;role:string;employeeName?:string;lastLogin?:string;locationScope:string[]};
const empty={displayName:"",username:"",email:"",role:"viewer",employeeName:"",locationScope:[] as string[]};
export default function UserManagement(){const {toast}=useToast();const [users,setUsers]=useState<User[]>([]),[roles,setRoles]=useState<any[]>([]),[search,setSearch]=useState(""),[tab,setTab]=useState("users"),[open,setOpen]=useState(false),[editing,setEditing]=useState<User|null>(null),[form,setForm]=useState<any>(empty),[passwordFor,setPasswordFor]=useState<User|null>(null),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [u,r]=await Promise.all([api(""),fetch(`${BASE}/api/settings/roles`,{credentials:"include"}).then(x=>x.ok?x.json():[])]);setUsers(u);setRoles(r)}catch(e:any){toast({title:"Unable to load user management",description:e.message,variant:"destructive"})}};useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>users.filter(u=>`${u.displayName} ${u.username} ${u.email||""} ${u.role} ${u.employeeName||""}`.toLowerCase().includes(search.toLowerCase())),[users,search]);
 const begin=(u?:User)=>{setEditing(u||null);setForm(u?{...u}:empty);setOpen(true)};
 const save=async()=>{setBusy(true);try{const body={name:form.displayName,displayName:form.displayName,username:form.username,email:form.email,role:form.role,employeeName:form.employeeName||null,locationScope:form.locationScope||[]};const result=await api(editing?`/${editing.id}`:"",{method:editing?"PATCH":"POST",body:JSON.stringify(body)});setOpen(false);await load();toast({title:editing?"User updated":"User created",description:result?.temporaryPassword?`One-time password: ${result.temporaryPassword}`:undefined})}catch(e:any){toast({title:"Unable to save user",description:e.message,variant:"destructive"})}finally{setBusy(false)}};
 const reset=async()=>{if(!passwordFor)return;setBusy(true);try{await api(`/${passwordFor.id}/reset-password`,{method:"POST",body:JSON.stringify({newPassword:password,confirmPassword:password})});setPasswordFor(null);setPassword("");toast({title:"Password reset",description:"Existing sessions for this user were invalidated."})}catch(e:any){toast({title:"Unable to reset password",description:e.message,variant:"destructive"})}finally{setBusy(false)}};
 const deactivate=async(u:User)=>{if(!window.confirm(`Deactivate ${u.displayName}?`))return;try{await api(`/${u.id}`,{method:"DELETE"});await load();toast({title:"User deactivated"})}catch(e:any){toast({title:"Unable to deactivate",description:e.message,variant:"destructive"})}};
 const sync=async()=>{try{const r=await api("/sync-roles",{method:"POST"});toast({title:"Users and roles synced",description:`${r.syncedUsers} user session(s) refreshed.`})}catch(e:any){toast({title:"Unable to sync",description:e.message,variant:"destructive"})}};
 return <div className="space-y-5"><Tabs value={tab} onValueChange={setTab}><div className="flex flex-wrap items-center justify-between gap-3"><TabsList><TabsTrigger value="users">Users</TabsTrigger><TabsTrigger value="roles">Roles</TabsTrigger></TabsList><div className="flex gap-2"><Button variant="outline" onClick={()=>void sync()}><RefreshCw className="mr-2 h-4 w-4"/>Sync users and roles</Button>{tab==="users"&&<Button onClick={()=>begin()}><Plus className="mr-2 h-4 w-4"/>New User</Button>}</div></div><TabsContent value="users" className="space-y-4"><div className="relative max-w-md"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search users…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="overflow-hidden rounded-lg border"><div className="hidden grid-cols-[2fr,1.5fr,1fr,1fr,auto] gap-4 border-b bg-muted/40 px-4 py-2 text-xs font-medium uppercase text-muted-foreground md:grid"><span>User</span><span>Email / Employee</span><span>Role</span><span>Last login</span><span>Actions</span></div>{filtered.map(u=><div key={u.id} className="grid gap-3 border-b p-4 last:border-0 md:grid-cols-[2fr,1.5fr,1fr,1fr,auto] md:items-center"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-primary/10 font-semibold text-primary">{u.displayName.charAt(0).toUpperCase()}</span><div><div className="font-medium">{u.displayName}</div><div className="text-xs text-muted-foreground">@{u.username}</div></div></div><div className="text-sm"><div>{u.email||"No email"}</div><div className="text-xs text-muted-foreground">{u.employeeName||"No linked employee"}</div></div><Badge variant="outline" className="w-fit capitalize">{u.role}</Badge><span className="text-sm text-muted-foreground">{u.lastLogin?relative(u.lastLogin):"Never"}</span><div className="flex"><Button size="icon" variant="ghost" title="Edit" onClick={()=>begin(u)}><Edit2 className="h-4 w-4"/></Button><Button size="icon" variant="ghost" title="Reset password" onClick={()=>setPasswordFor(u)}><KeyRound className="h-4 w-4"/></Button><Button size="icon" variant="ghost" title="Deactivate" className="text-destructive" onClick={()=>void deactivate(u)}><UserX className="h-4 w-4"/></Button></div></div>)}{!filtered.length&&<div className="p-10 text-center text-sm text-muted-foreground">No users found.</div>}</div></TabsContent><TabsContent value="roles"><RolesPage/></TabsContent></Tabs>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing?"Edit User":"New User"}</DialogTitle></DialogHeader><div className="grid gap-4 py-2 sm:grid-cols-2"><Field label="Full name"><Input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></Field><Field label="Username"><Input value={form.username} onChange={e=>setForm({...form,username:e.target.value.toLowerCase()})}/></Field><Field label="Email"><Input type="email" value={form.email||""} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Employee name/link"><Input value={form.employeeName||""} onChange={e=>setForm({...form,employeeName:e.target.value})}/></Field><Field label="Role"><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.filter(r=>!r.isSuperAdmin&&r.name!=="admin").map(r=><option key={r.id} value={r.name}>{r.name}</option>)}</select></Field></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy||!form.displayName.trim()||(!form.username.trim()&&!form.email.trim())} onClick={()=>void save()}>{busy?"Saving…":"Save User"}</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={!!passwordFor} onOpenChange={v=>!v&&setPasswordFor(null)}><DialogContent><DialogHeader><DialogTitle>Reset password for {passwordFor?.displayName}</DialogTitle></DialogHeader><Field label="New password (minimum 8 characters)"><Input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></Field><DialogFooter><Button variant="outline" onClick={()=>setPasswordFor(null)}>Cancel</Button><Button disabled={busy||password.length<8} onClick={()=>void reset()}>Reset password</Button></DialogFooter></DialogContent></Dialog></div>}
function Field({label,children}:{label:string;children:any}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function relative(value:string){const seconds=Math.floor((Date.now()-new Date(value).getTime())/1000);if(seconds<60)return "Just now";if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`}
