import {
  boolean,
  date,
  integer,
  mongoTable,
  numeric,
  serial,
  text,
  timestamp,
} from "./dsl";
const org = () => ({
  organizationId: integer("organization_id").notNull().default(1),
});
export const chartOfAccountsTable = mongoTable("chart_of_accounts", {
  ...org(),
  id: serial("id").primaryKey(),
  accountCode: text("account_code").notNull(),
  accountName: text("account_name").notNull(),
  accountType: text("account_type").notNull(),
  currentBalance: numeric("current_balance").notNull().default("0"),
  parentId: integer("parent_id"),
  description: text("description").default(""),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const journalEntriesTable = mongoTable("journal_entries", {
  ...org(),
  id: serial("id").primaryKey(),
  entryDate: date("entry_date").notNull(),
  reference: text("reference").notNull(),
  description: text("description").notNull(),
  totalDebit: numeric("total_debit").notNull(),
  totalCredit: numeric("total_credit").notNull(),
  status: text("status").notNull().default("Posted"),
  sourceType: text("source_type").default("Manual"),
  sourceId: integer("source_id"),
  createdByUserId: integer("created_by_user_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const journalLinesTable = mongoTable("journal_lines", {
  ...org(),
  id: serial("id").primaryKey(),
  journalEntryId: integer("journal_entry_id")
    .notNull()
    .references(() => journalEntriesTable.id, { onDelete: "cascade" }),
  accountId: integer("account_id")
    .notNull()
    .references(() => chartOfAccountsTable.id),
  accountCode: text("account_code").notNull(),
  accountName: text("account_name").notNull(),
  debit: numeric("debit").notNull().default("0"),
  credit: numeric("credit").notNull().default("0"),
  memo: text("memo").default(""),
});
export const accountsPayableTable = mongoTable("accounts_payable", {
  ...org(),
  id: serial("id").primaryKey(),
  vendorName: text("vendor_name").notNull(),
  billNumber: text("bill_number").notNull(),
  againstBillNumber: text("against_bill_number").default(""),
  billDate: date("bill_date").notNull(),
  dueDate: date("due_date").notNull(),
  amount: numeric("amount").notNull(),
  paidAmount: numeric("paid_amount").notNull().default("0"),
  adjustedAmount: numeric("adjusted_amount").notNull().default("0"),
  status: text("status").notNull().default("Pending"),
  approvalStatus: text("approval_status").notNull().default("Pending Approval"),
  requiredApprovals: integer("required_approvals").notNull().default(1),
  approvalLevel: integer("approval_level").notNull().default(0),
  approvedByUserIds: text("approved_by_user_ids").notNull().default("[]"),
  approvalRemarks: text("approval_remarks").default(""),
  reason: text("reason").default(""),
  appliedAmount: numeric("applied_amount").notNull().default("0"),
  availableCredit: numeric("available_credit").notNull().default("0"),
  entryType: text("entry_type").notNull().default("Bill"),
  notes: text("notes").default(""),
  journalEntryId: integer("journal_entry_id"),
  sourceType: text("source_type"),
  sourceId: integer("source_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const accountsReceivableTable = mongoTable("accounts_receivable", {
  ...org(),
  id: serial("id").primaryKey(),
  clientId: integer("client_id"),
  clientName: text("client_name").notNull(),
  creditNoteNumber: text("credit_note_number").default(""),
  invoiceNumber: text("invoice_number").notNull(),
  linkedInvoiceNumber: text("linked_invoice_number").default(""),
  invoiceDate: date("invoice_date").notNull(),
  dueDate: date("due_date").notNull(),
  amount: numeric("amount").notNull(),
  receivedAmount: numeric("received_amount").notNull().default("0"),
  adjustedAmount: numeric("adjusted_amount").notNull().default("0"),
  status: text("status").notNull().default("Pending"),
  approvalStatus: text("approval_status").notNull().default("Pending Approval"),
  requiredApprovals: integer("required_approvals").notNull().default(1),
  approvalLevel: integer("approval_level").notNull().default(0),
  approvedByUserIds: text("approved_by_user_ids").notNull().default("[]"),
  approvalRemarks: text("approval_remarks").default(""),
  entryType: text("entry_type").notNull().default("Invoice"),
  notes: text("notes").default(""),
  journalEntryId: integer("journal_entry_id"),
  sourceType: text("source_type"),
  sourceId: integer("source_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const partyLedgerEntriesTable = mongoTable("party_ledger_entries", {
  ...org(),
  id: serial("id").primaryKey(),
  partyType: text("party_type").notNull(),
  clientId: integer("client_id"),
  clientName: text("client_name").default(""),
  vendorName: text("vendor_name").default(""),
  entryType: text("entry_type").notNull(),
  amount: numeric("amount").notNull(),
  drCr: text("dr_cr").notNull(),
  entryDate: date("entry_date").notNull(),
  reference: text("reference").notNull(),
  notes: text("notes").default(""),
  journalEntryId: integer("journal_entry_id"),
  linkedArId: integer("linked_ar_id"),
  linkedApId: integer("linked_ap_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
export const transactionsTable = mongoTable("account_transactions", {
  ...org(),
  id: serial("id").primaryKey(),
  date: date("date").notNull(),
  description: text("description").notNull(),
  category: text("category").notNull(),
  type: text("type").notNull(),
  amount: numeric("amount").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
