import {
  boolean,
  date,
  integer,
  json,
  mongoTable,
  numeric,
  serial,
  text,
  timestamp,
} from "./dsl";
const org = () => ({
  organizationId: integer("organization_id").notNull().default(1),
});
export const chartOfAccountsTable = mongoTable("chart_of_accounts", {
  ...org(),
  id: serial("id").primaryKey(),
  accountCode: text("account_code").notNull(),
  accountName: text("account_name").notNull(),
  accountType: text("account_type").notNull(),
  currentBalance: numeric("current_balance").notNull().default("0"),
  parentId: integer("parent_id"),
  groupName: text("group_name").default(""),
  tallyLedgerName: text("tally_ledger_name").default(""),
  tallyGroupName: text("tally_group_name").default(""),
  isBankCash: boolean("is_bank_cash").notNull().default(false),
  bankAccountNumber: text("bank_account_number").default(""),
  bankIfsc: text("bank_ifsc").default(""),
  bankName: text("bank_name").default(""),
  openingBalance: numeric("opening_balance").notNull().default("0"),
  openingBalanceDate: date("opening_balance_date"),
  description: text("description").default(""),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const journalEntriesTable = mongoTable("journal_entries", {
  ...org(),
  id: serial("id").primaryKey(),
  entryDate: date("entry_date").notNull(),
  reference: text("reference").notNull(),
  description: text("description").notNull(),
  totalDebit: numeric("total_debit").notNull(),
  totalCredit: numeric("total_credit").notNull(),
  status: text("status").notNull().default("Posted"),
  approvalStatus: text("approval_status").notNull().default("Approved"),
  requiredApprovals: integer("required_approvals").notNull().default(1),
  approvalLevel: integer("approval_level").notNull().default(1),
  approvedByUserIds: text("approved_by_user_ids").notNull().default("[]"),
  approvalRemarks: text("approval_remarks").default(""),
  rejectedByUserId: integer("rejected_by_user_id"),
  rejectedAt: timestamp("rejected_at"),
  rejectionRemarks: text("rejection_remarks").default(""),
  voucherType: text("voucher_type").notNull().default("Journal"),
  tallyVoucherType: text("tally_voucher_type").default("Journal"),
  tallyGuid: text("tally_guid").default(""),
  tallyImportBatchId: text("tally_import_batch_id").default(""),
  tallyExportedAt: timestamp("tally_exported_at"),
  metadata: json("metadata").notNull().default({}),
  sourceType: text("source_type").default("Manual"),
  sourceId: integer("source_id"),
  createdByUserId: integer("created_by_user_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const journalLinesTable = mongoTable("journal_lines", {
  ...org(),
  id: serial("id").primaryKey(),
  journalEntryId: integer("journal_entry_id")
    .notNull()
    .references(() => journalEntriesTable.id, { onDelete: "cascade" }),
  accountId: integer("account_id")
    .notNull()
    .references(() => chartOfAccountsTable.id),
  accountCode: text("account_code").notNull(),
  accountName: text("account_name").notNull(),
  debit: numeric("debit").notNull().default("0"),
  credit: numeric("credit").notNull().default("0"),
  memo: text("memo").default(""),
});
export const accountsPayableTable = mongoTable("accounts_payable", {
  ...org(),
  id: serial("id").primaryKey(),
  vendorName: text("vendor_name").notNull(),
  billNumber: text("bill_number").notNull(),
  againstBillNumber: text("against_bill_number").default(""),
  billDate: date("bill_date").notNull(),
  dueDate: date("due_date").notNull(),
  amount: numeric("amount").notNull(),
  paidAmount: numeric("paid_amount").notNull().default("0"),
  adjustedAmount: numeric("adjusted_amount").notNull().default("0"),
  status: text("status").notNull().default("Pending"),
  approvalStatus: text("approval_status").notNull().default("Pending Approval"),
  requiredApprovals: integer("required_approvals").notNull().default(1),
  approvalLevel: integer("approval_level").notNull().default(0),
  approvedByUserIds: text("approved_by_user_ids").notNull().default("[]"),
  approvalRemarks: text("approval_remarks").default(""),
  reason: text("reason").default(""),
  appliedAmount: numeric("applied_amount").notNull().default("0"),
  availableCredit: numeric("available_credit").notNull().default("0"),
  entryType: text("entry_type").notNull().default("Bill"),
  notes: text("notes").default(""),
  journalEntryId: integer("journal_entry_id"),
  sourceType: text("source_type"),
  sourceId: integer("source_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const accountsReceivableTable = mongoTable("accounts_receivable", {
  ...org(),
  id: serial("id").primaryKey(),
  clientId: integer("client_id"),
  clientName: text("client_name").notNull(),
  creditNoteNumber: text("credit_note_number").default(""),
  invoiceNumber: text("invoice_number").notNull(),
  linkedInvoiceNumber: text("linked_invoice_number").default(""),
  invoiceDate: date("invoice_date").notNull(),
  dueDate: date("due_date").notNull(),
  amount: numeric("amount").notNull(),
  receivedAmount: numeric("received_amount").notNull().default("0"),
  adjustedAmount: numeric("adjusted_amount").notNull().default("0"),
  status: text("status").notNull().default("Pending"),
  approvalStatus: text("approval_status").notNull().default("Pending Approval"),
  requiredApprovals: integer("required_approvals").notNull().default(1),
  approvalLevel: integer("approval_level").notNull().default(0),
  approvedByUserIds: text("approved_by_user_ids").notNull().default("[]"),
  approvalRemarks: text("approval_remarks").default(""),
  entryType: text("entry_type").notNull().default("Invoice"),
  notes: text("notes").default(""),
  journalEntryId: integer("journal_entry_id"),
  sourceType: text("source_type"),
  sourceId: integer("source_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
export const partyLedgerEntriesTable = mongoTable("party_ledger_entries", {
  ...org(),
  id: serial("id").primaryKey(),
  partyType: text("party_type").notNull(),
  clientId: integer("client_id"),
  clientName: text("client_name").default(""),
  vendorName: text("vendor_name").default(""),
  entryType: text("entry_type").notNull(),
  amount: numeric("amount").notNull(),
  drCr: text("dr_cr").notNull(),
  entryDate: date("entry_date").notNull(),
  reference: text("reference").notNull(),
  notes: text("notes").default(""),
  journalEntryId: integer("journal_entry_id"),
  linkedArId: integer("linked_ar_id"),
  linkedApId: integer("linked_ap_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
export const transactionsTable = mongoTable("account_transactions", {
  ...org(),
  id: serial("id").primaryKey(),
  date: date("date").notNull(),
  description: text("description").notNull(),
  category: text("category").notNull(),
  type: text("type").notNull(),
  amount: numeric("amount").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const accountGroupsTable = mongoTable("account_groups", {
  ...org(),
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  parentName: text("parent_name").default(""),
  tallyGroupName: text("tally_group_name").default(""),
  accountType: text("account_type").notNull().default("Asset"),
  isSystem: boolean("is_system").notNull().default(false),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const accountCostCentersTable = mongoTable("account_cost_centers", {
  ...org(),
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  code: text("code").notNull(),
  description: text("description").default(""),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const accountTransactionTypesTable = mongoTable("account_transaction_types", {
  ...org(),
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  code: text("code").notNull(),
  direction: text("direction").notNull().default("Either"),
  defaultDebitAccountId: integer("default_debit_account_id"),
  defaultCreditAccountId: integer("default_credit_account_id"),
  tallyVoucherType: text("tally_voucher_type").notNull().default("Journal"),
  isSystem: boolean("is_system").notNull().default(false),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const bankCashTransactionsTable = mongoTable("bank_cash_transactions", {
  ...org(),
  id: serial("id").primaryKey(),
  transactionDate: date("transaction_date").notNull(),
  transactionTypeId: integer("transaction_type_id"),
  transactionTypeName: text("transaction_type_name").notNull(),
  mode: text("mode").notNull().default("Credit"),
  bankCashAccountId: integer("bank_cash_account_id").notNull().references(() => chartOfAccountsTable.id),
  transferToAccountId: integer("transfer_to_account_id"),
  counterAccountId: integer("counter_account_id"),
  amount: numeric("amount").notNull(),
  reference: text("reference").notNull(),
  remarks: text("remarks").default(""),
  status: text("status").notNull().default("Pending Approval"),
  approvalStatus: text("approval_status").notNull().default("Pending Approval"),
  requiredApprovals: integer("required_approvals").notNull().default(1),
  approvalLevel: integer("approval_level").notNull().default(0),
  approvedByUserIds: text("approved_by_user_ids").notNull().default("[]"),
  approvalRemarks: text("approval_remarks").default(""),
  rejectedByUserId: integer("rejected_by_user_id"),
  rejectedAt: timestamp("rejected_at"),
  rejectionRemarks: text("rejection_remarks").default(""),
  journalEntryId: integer("journal_entry_id"),
  createdByUserId: integer("created_by_user_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const accountDocumentsTable = mongoTable("account_documents", {
  ...org(),
  id: serial("id").primaryKey(),
  sourceType: text("source_type").notNull(),
  sourceId: integer("source_id").notNull(),
  journalEntryId: integer("journal_entry_id"),
  fileName: text("file_name").notNull(),
  originalName: text("original_name").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull().default(0),
  url: text("url").notNull(),
  uploadedByUserId: integer("uploaded_by_user_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});